-- Comentarios de una sola línea
-- Comentarios de una línea con dos guiones medios seguidos --
/* Comentarios
de
múltiples
líneas
*/

-- SQL (LENGUAJE DE CONSULTA ESTRUCTURADO)
-- Bases de datos relacionales - conjunto de datos relacionados
-- entre sí y que son almacenados en tablas

-- ESTRUCTURA DE UNA TABLA EN BD
-- Toda tabla debe llevar llave primaria - Primary key   (ID)
-- Que es un identificador único de cada registro que vamos guardando
-- Puede llevar llave foránea - Foreing key  (algunas)
-- La llave foránea es una llave primaria que proviene de otra tabla
-- Columnas con su diferente tipo de dato

-- TIPOS DE DATOS EN BD ORACLE
-- NUMBER - Permite almacenar datos numéricos enteros y decimales
-- VARCHAR2 - NVARCHAR2 - Este último admite caracteres alfanuméricos
-- y caracteres especiales y además optimiza la memoria 
-- DATE - Manejo de fecha y hora
-- ctrl + s para guardar nuestro script sql

-- vamos a crear una primera tabla de ejemplo para guardar 
-- la info de alumnos de una escuela o universidad

-- Sintaxis para crear una tabla es la sig:

/*
CREATE TABLA nombreTabla (
nombreColumna tipoDato,
columna2 tipoDato,
.
.
);
*/

-- ALUMNOS
-- MATRICULA O ID DEL ALUMNO
-- NOMBRE
-- FECHA DE NACIMIENTO
-- GENERO
-- GRADO
-- CIUDAD
-- STATUS - ESTE SERÁ NUMÉRICO PARA SABER SI EL ALUMNO ESTÁ
-- INSCRITO (1) O NO (0)

-- Se recomienda que las sentencias sql se escriban en mayúsculas
-- porque luego esto lo comunicaremos con java y entonces existe
-- sensibilidad al uso de mayúsculas y minúsculas

CREATE TABLE ALUMNO(
ALUMNO_ID NUMBER PRIMARY KEY, 
NOMBRE NVARCHAR2(30),
FECHANAC DATE, 
GENERO NVARCHAR2(18),
GRADO NVARCHAR2 (30),
CIUDAD NVARCHAR2 (30),
STATUS NUMBER
);

-- VER LA ESTRUCTURA DE UNA TABLA
DESCRIBE ALUMNO;

-- RENOMBRAR UNA TABLA
ALTER TABLE ALUMNO RENAME TO ALUMNOS;

-- ELIMINAR UNA TABLA CON TODO Y SU CONTENIDO
DROP TABLE ALUMNOS;

-- CREAR UNA TABLA PARA ALMACENAR CARRERAS
CREATE TABLE CARRERAS(
CARRERA_ID NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(30),
AREA NVARCHAR2(30),
DURACION NVARCHAR2(30)
);

DESCRIBE CARRERAS;

-- RENOMBRAR UNA COLUMNA DE UNA TABLA
ALTER TABLE CARRERAS RENAME COLUMN DURACION TO SEMESTRES;

-- AGREGAR UNA COLUMNA A UNA TABLA EXISTENTE CON UN TIPO DE DATO
-- DELIMITADO (NUMBER), 8 POSICIONES NUMÉRICAS Y DE ELLAS 2 SON DECIMALES
ALTER TABLE CARRERAS ADD PRESUPUESTO NUMBER (8,2);

-- MODIFICAR EL TIPO DE DATO DE UNA COLUMNA, SIEMPRE Y CUANDO
-- NO TENGA DATOS
ALTER TABLE CARRERAS MODIFY SEMESTRES NUMBER;
 
DESCRIBE CARRERAS;

ALTER TABLE CARRERAS MODIFY SEMESTRES NVARCHAR2(50);

-- CREAR UNA TERCERA TABLA RELACIONAL PARA TENER LA POSIBILIDAD 
-- DE UNA CARDINALIDAD 1 A MUCHOS 1:M (1 ALUMNOS Y MUCHAS O VARIAS CARRERAS)

CREATE TABLE CARRERAS_ALUMNOS(
CA_ID NUMBER PRIMARY KEY,
ALUMNO_ID NUMBER,
CARRERA_ID NUMBER
);

-- CREACIÓN DE RESTRICCIONES
-- NOS VA A PERMITIR INTRODUCIR SOLO DETERMINADOS VALORES EN NUESTRAS COLUMNAS

-- RESTRICCIONES DE TIPO CHECK (VALIDAN O VERIFICAN UN VALOR)
-- EJ. EN LA TABLA ALUMNO VAMOS A CREAR UNA RESTRICCIÓN PARA QUE EN LA COLUNMNA GENERO
-- SOLO PODAMOS INSERTAR EL VALOR MASCULINO O FEMENINO

ALTER TABLE ALUMNO  ADD CONSTRAINT CHK_GENERO 
CHECK (GENERO IN('MASCULINO', 'FEMENINO'));

DESCRIBE ALUMNO;

CREATE TABLE compras(

-- EJEMPLO, podemos escribir las sentencias con minúsculas, pero las columnas
-- y tablas se crean los nombres con mayúsculas
-- Por lo que se recomienda en todas las sentencias el uso de mayúsculas
compra_id number primary key,
nombre  nvarchar2(30)
);

-- RESTRICCIONES UNIQUE
-- SIRVEN PARA EVITAR QUE UN VALOR QUE NO ES LLAVE PRIMARIA
-- SE REPITA. EJ. EL NOMBRE DE LAS CARRERAS

ALTER TABLE CARRERAS ADD CONSTRAINT UNQ_NOMBRE_CARRERAS
UNIQUE (NOMBRE);

-- ELIMINAR UNA RESTRICCIÓN EN CASO DE ALGÚN ERROR
ALTER TABLE CARRERAS DROP CONSTRAINT UNQ_NOMBRE_CARRERAS;

-- RESTRICCIÓN DE LLAVES FORÁNEAS
-- ESTABLECEN LA RELACIÓN DE LA INFORMACIÓN EN OTRAS TABLAS
-- MEDIANTE LAS LLAVES PRIMARIAS
-- ESTO HACE QUE LOS DATOS EN LAS TABLAS RELACIONALES DEPENDAN DE LA EXISTENCIA
-- PREVIA EN LAS OTRAS TABLAS

-- EJ. CREANDO LAS LLAVES FORÁNEAS EN LA TABLA CARRERAS_ALUMNOS
-- PRIMERO LA LLAVE FORÁNEA PARA RECIBIR LA INFO DEL ALUMNO

ALTER TABLE CARRERAS_ALUMNOS ADD CONSTRAINT FK_ALUMNO_ID_CA
FOREIGN KEY (ALUMNO_ID)
REFERENCES ALUMNO (ALUMNO_ID);

-- SEGUNDO LA LLAVE FORÁNEA PARA RECIBIR LA INFO DE LA CARRERA
ALTER TABLE CARRERAS_ALUMNOS ADD CONSTRAINT FK_CARRERA_ID_CA
FOREIGN KEY (CARRERA_ID)
REFERENCES CARRERAS (CARRERA_ID);

DESCRIBE CARRERAS;

-- SENTENCIAS DML (DATA MANIPULATION LANGUAJE)
-- comandos que nos permiten realizar operaciones CRUD en nuestras tablas
-- Create, Read, Update, Delete (Crear, leer o consultar, actualizar y eliminar)

-- vamos a insertar nuestros primeros registros en nuestras tablas
-- Ej. Insertar un primer alumno
-- Antes de crear el primer registro, vamos a verificar el formato de fecha
-- que admite nuestro sistema

SELECT SYSDATE FROM DUAL;

-- INSERTAMOS NUESTRO PRIMER REGISTRO EN LA TABLA ALUMNO
INSERT INTO ALUMNO VALUES (1, 'ANDRES', '26/03/1994', 'MASCULINO', '1ER SEMESTRE', 'CDMX', 1);
INSERT INTO ALUMNO VALUES (2, 'ALEX', '24/04/2000', 'MASCULINO', '3ER SEMESTRE', 'PUEBLA', 1);
INSERT INTO ALUMNO VALUES (3, 'CARMEN', '02/07/2002', 'FEMENINO', '1ER SEMESTRE', 'OAXACA', 1);

-- CONSULTA GENERAL DE TODAS LAS COLUMNAS DE UNA TABLA

SELECT * FROM ALUMNO; 

-- LAS SENTENCIAS DML, QUE SON DE MANIPULACIÓN DE DATOS SE DEBEN CONFIRMAR PARA QUE
-- ESTOS CAMBIOS SE GUARDEN DE FORMA PERMANENTE EN LA BD
COMMIT; 

--INSERTAR VALORES EN LA TABLA CARRERAS

DESCRIBE CARRERAS;

INSERT INTO CARRERAS VALUES(1, 'ING EN SISTEMAS', 'EXACTAS', '8 SEMESTRES', 200000.99);
INSERT INTO CARRERAS VALUES(2, 'MEDICINA', 'BIOLOGICAS', '10 SEMESTRES', 300000.99);
INSERT INTO CARRERAS VALUES(3, 'ADMINISTRACION', 'ECONOMICAS', '8 SEMESTRES', 100000.99);
    
-- EJ DE QUE NO SE PUEDEN REPETIR LOS NOMBRES DE LAS CARRERAS Y FUNCIONA LA RESTRICCIÓN
-- UNIQUE
INSERT INTO CARRERAS VALUES(3, 'ADMINISTRACION', 'ECONOMICAS', '8 SEMESTRES', 100000.99);

COMMIT;

SELECT * FROM CARRERAS;

-- INSERTAR VALORES EN LA TABLA RELACIONAL CARRERAS_ALUMNOS
DESCRIBE CARRERAS_ALUMNOS;

INSERT INTO CARRERAS_ALUMNOS VALUES (1, 1, 3);
INSERT INTO CARRERAS_ALUMNOS VALUES (2, 2, 3);
INSERT INTO CARRERAS_ALUMNOS VALUES (3, 3, 1);

COMMIT;
SELECT * FROM CARRERAS_ALUMNOS;

SELECT * FROM STATUS_ALUMNOS;
-- EJERCICIO TUTORES Y TUTORES ALUMNOS, STATUS ALUMNOS
-- EJ. DE SINTAXIS PARA CREAR MIS TABLAS YA CON SU RESTRICCIÓN
CREATE TABLE TUTORES(
TUTOR_ID NUMBER PRIMARY KEY, 
NOMBRE NVARCHAR2(30),
EMAIL NVARCHAR2(30),
CLAVE NVARCHAR2(1)
--CONSTRAINT CHK_CLAVE_TUTOR 
--CHECK (CLAVE IN('A', 'B', 'C', 'D'))
);

ALTER TABLE TUTORES ADD CONSTRAINT CHK_CLAVE 
CHECK (CLAVE IN('A', 'B', 'C', 'D'));

INSERT INTO TUTORES VALUES (1, 'MIGUEL', 'miguel@gmail.com', 'A');
INSERT INTO TUTORES VALUES (2, 'LUIS', 'luis@gmail.com', 'B');
INSERT INTO TUTORES VALUES (3, 'ANGEL', 'angel@gmail.com', 'C');
INSERT INTO TUTORES VALUES (4, 'REBECA', 'rebeca@gmail.com', 'D');
INSERT INTO TUTORES VALUES (5, 'SARAI', 'sarai@gmail.com', 'A');

COMMIT;

SELECT * FROM TUTORES;
SELECT * FROM TUTORES_ALUMNOS;

-- EJ. DE CREACIÓN DE LA TABLA TUTORES_ALUMNOS YA CON SUS RESTRICCIONES DE LLAVE FORÁNEA
-- CREADAS
CREATE TABLE TUTORES_ALUMNOS(
TA_ID NUMBER PRIMARY KEY,
TUTOR_ID NUMBER,
ALUMNO_ID NUMBER
--CONSTRAINT FK_TUTOR_ID_TA 
--FOREIGN KEY (TUTOR_ID)
--REFERENCES TUTORES (TUTOR_ID);
--CONSTRAINT FK_ALUMNO_ID_TA 
--FOREIGN KEY (ALUMNO_ID)
--REFERENCES ALUMNO (ALUMNO_ID);
);

ALTER TABLE TUTORES_ALUMNOS ADD CONSTRAINT FK_TUTOR_ID_TA
FOREIGN KEY (TUTOR_ID)
REFERENCES TUTORES (TUTOR_ID);

ALTER TABLE TUTORES_ALUMNOS ADD CONSTRAINT FK_ALUMNO_ID_TA
FOREIGN KEY (ALUMNO_ID)
REFERENCES ALUMNO (ALUMNO_ID);

-- INSERCIÓN EN LA TABLA RELACIONAL TUTORES_ALUMNOS
INSERT INTO TUTORES_ALUMNOS VALUES (1,5,1);
INSERT INTO TUTORES_ALUMNOS VALUES (2,5,2);
INSERT INTO TUTORES_ALUMNOS VALUES (3,3,3);

COMMIT;

SELECT * FROM TUTORES_ALUMNOS;

-- CREACIÓN DE LA TABLA STATUS_ALUMNOS NOS VA A SERVIR COMO CATÁLOGO PARA SABER
-- QUÉ SIGNIFICAN LOS STATUS DE CADA ALUMNO Y ADEMÁS SI CREAMOS LA LLAVE FORÁNEA
-- EN LA TABLA ALUMNO, PUES RESTRINGIMOS QUE SOLO PUEDAN TOMARSE VALORES PREVIAMENTE
-- EXISTENTES EN STATUS_ALUMNOS
 
CREATE TABLE STATUS_ALUMNOS(
STATUS_ID NUMBER PRIMARY KEY,
DESCRIPCION NVARCHAR2(30)
);

-- PRIMERO DEBEMOS INSERTAR LOS IDS, QUE YA EXISTEN EN LA TABLA ALUMNO
-- ANTES DE CREAR LA LLAVE FORÁNEA

INSERT INTO STATUS_ALUMNOS VALUES (0, 'ALUMNO NO INSCRITO');
INSERT INTO STATUS_ALUMNOS VALUES (1, 'ALUMNO INSCRITO');

COMMIT;

SELECT * FROM STATUS_ALUMNOS;

ALTER TABLE ALUMNO ADD CONSTRAINT FK_STATUS_ALUMNO
FOREIGN KEY (STATUS)
REFERENCES STATUS_ALUMNOS (STATUS_ID);

COMMIT;

SELECT * FROM STATUS_ALUMNOS;


-- CREACIÓN DE SECUENCIAS
-- LAS SECUENCIAS SON OBJETOS QUE NOS PERMITEN GENERAR VALORES DE 
-- NÚMEROS ENTEROS EN FORMA CONSECUTIVA CON UN INCREMENTO DETERMINADO
-- (DE 1 EN 1, DE 2 EN 2, ETC)
-- SE UTILIZAN PARA EN ESTE CASO, GENERAR LAS LLAVES PRIMARIAS Y DE ESTA
-- FORMA ASEGURAMOS AÚN MÁS QUE LOS VALORES NO SE REPITAN

-- VAMOS A CREAR UNA SECUENCIA PARA UNA TABLA QUE YA TIENE REGISTROS
-- INSERTADOS. SE CREA UNA SECUENCIA CON VALORES DEFINIDOS

SELECT * FROM ALUMNO;

CREATE SEQUENCE ALUMNO_SEQ
START WITH 5
INCREMENT BY 1
MAXVALUE 999
MINVALUE 1
NOCYCLE;

-- EJ. DE CREAR UNA SECUENCIA CON VALORES DEFAULT. LA CUAL ES ÚTIL
-- PARA TABLAS QUE NO TIENEN DATOS AGREGADOS
CREATE SEQUENCE COMPRAS_SEQ;

-- CREACIÓN DE TRIGGERS O DISPARADORES
-- SON UN TIPO DE PROCEDIMIENTO ALMACENADO QUE DESENCANEDA UN EVENTO
-- EN ESTE CASO LO UTILIZAREMOS PARA INSERTAR LAS LLAVES PRIMARIAS
-- EJ. CREACIÓN DEL DISPARADOR  PARA INSERTAR LOS ID'S EN LA TABLA ALUMNO

CREATE OR REPLACE TRIGGER INSERT_ALUMNO
BEFORE INSERT ON ALUMNO FOR EACH ROW BEGIN
SELECT ALUMNO_SEQ.NEXTVAL INTO:NEW.ALUMNO_ID FROM DUAL;
END;

-- EJ. INSERTAR UN NUEVO ALUMNO, PERO EXPERIMENTANDO COMO EL TIGGER YA HACE
-- LA INSERCIÓN DEL ID POR NOSOTROS

INSERT INTO ALUMNO
VALUES (1, 'HUGO', '12/12/2002', 'MASCULINO', '4° SEMESTRE', 'CHIAPAS', 1);

SELECT * FROM ALUMNO;

-- EJ. QUÉ PASA SI QUIERO REGISTRAR UN NUEVO ALUMNO Y OMITIR EL ID
INSERT INTO ALUMNO 
VALUES ('ALMA', '12/12/2002', 'FEMENINO', '4° SEMESTRE', 'CHIAPAS', 1);

-- PUEDO OMITIR EL ID, INDICANDO QUÉ COLUMNAS VOY A INSERTAR ÚNICAMENTE
INSERT INTO ALUMNO (NOMBRE, FECHANAC, GENERO, GRADO, CIUDAD, STATUS) VALUES
('ALMA', '12/12/2002', 'FEMENINO', '4° SEMESTRE', 'CHIAPAS', 1);

SELECT * FROM ALUMNO;

COMMIT;

-- ELIMINAR UN REGISTRO DE UNA TABLA. CASI SIEMPRE ES RECOMENDABLE IDENTIFICAR
-- A NUESTRO REGISTRO A ELIMINAR POR ID
DELETE FROM ALUMNO WHERE ALUMNO_ID=28;

-- SI QUERMOS RECUPERAR UN REGISTRO ELIMINADO O UNA ACTUALIZACIÓN, HAY UNA 
-- INSTRUCCIÓN QUE NOS LLEVA AL ESTADO DEL ÚLTIMO COMMIT. EJ. AQUÍ AÚN NO HE CONFIRMADO
-- EL BORRADO DE MIS ALUMNOS
ROLLBACK;

SELECT * FROM ALUMNO;
COMMIT;

DELETE FROM ALUMNO WHERE ALUMNO_ID=44;

-- PODEMOS EDITAR LA SECUENCIA  SI QUEREMOS RECUPERAR EL CONSECUTIVO DE NÚMEROS
-- LO HACEMOS DESDE EL PANEL DE CONEXIONES EN EL APARTADO DE SECUENCIAS

-- ACTUALIZAR VALORES DE UN REGISTRO
-- EJ. VOY A EDITAR DE ALMA LA CIUDAD
UPDATE ALUMNO SET CIUDAD='CHIHUAHUA', WHERE ALUMNO_ID=5;

SELECT * FROM ALUMNO;

-- CONFIRMAMOS EL CAMBIO
COMMIT;

-- EJ. DE ACTUALIZACIÓN DE VARIOS VALORES AL MISMO TIEMPO
UPDATE ALUMNO SET CIUDAD='XALAPA', GRADO='5° SEMESTRE', STATUS=0 WHERE ALUMNO_ID=5;

SELECT * FROM ALUMNO;
COMMIT;

-- VAMOS A VER QUÉ OCURRE SI CREO UNA SECUENCIA CON VALORES POR DEFECTO
-- ES DECIR, QUE INICIE DESDE EL 1, Y CREO TAMBIÉN UN DISPARADOR
-- EJ. PARA LA TABLA CARRERAS
CREATE SEQUENCE CARRERAS_SEQ;

SELECT * FROM CARRERAS;
COMMIT;

-- CREAR EL TIGGER PARA LA TABLA CARRERAS
CREATE OR REPLACE TRIGGER INSERT_CARRERAS
BEFORE INSERT ON CARRERAS FOR EACH ROW BEGIN
SELECT CARRERAS_SEQ.NEXTVAL INTO:NEW.CARRERA_ID FROM DUAL;
END;

-- INTENTAMOS INSERTAR UNA CARRERA, EL DISPARADOR LO INTENTARÁ INSERTAR CON EL ID 1
-- ASÍ QUE TENDREMOS QUE LLEVAR AL VALOR HASTA QUE SEA CORRECTO 
INSERT INTO CARRERAS VALUES(1, 'GASTRONOMÍA', 'ECONÓMICAS', '9 SEMESTRES', 110000.80);

----------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------EJERCICIO BIBLIOTECA--------------------------------------------

CREATE TABLE LIBROS(
LIBROS_ID NUMBER PRIMARY KEY, 
TITULO NVARCHAR2(30),
CANTIDAD_COPIAS NUMBER
);

COMMIT;

CREATE SEQUENCE LIBROS_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999
MINVALUE 1
NOCYCLE;

CREATE OR REPLACE TRIGGER INSERT_LIBROS
BEFORE INSERT ON LIBROS FOR EACH ROW BEGIN
SELECT LIBROS_SEQ.NEXTVAL INTO:NEW.LIBROS_ID FROM DUAL;
END;

INSERT INTO LIBROS VALUES (1, 'LOS MISERABLES',50);
INSERT INTO LIBROS VALUES (1, 'EL PRINCIPITO',100);
INSERT INTO LIBROS VALUES (1, 'EL PRINCIPE',150);
INSERT INTO LIBROS VALUES (1, 'BLANCA NIEVES',200);
INSERT INTO LIBROS VALUES (1, 'HERCULES',250);

SELECT * FROM LIBROS;

COMMIT;

CREATE TABLE AUTORES(
AUTORES_ID NUMBER PRIMARY KEY, 
NOMBRE NVARCHAR2(30),
NACIONALIDAD NVARCHAR2(30)
);

COMMIT;

CREATE SEQUENCE AUTORES_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999
MINVALUE 1
NOCYCLE;

CREATE OR REPLACE TRIGGER INSERT_AUTORES
BEFORE INSERT ON AUTORES FOR EACH ROW BEGIN
SELECT AUTORES_SEQ.NEXTVAL INTO:NEW.AUTORES_ID FROM DUAL;
END;                       

INSERT INTO AUTORES VALUES (1, 'VÍCTOR HUGO','FRANCIA');
INSERT INTO AUTORES VALUES (1, 'Antoine de Saint-Exupéry','FRANCIA');
INSERT INTO AUTORES  VALUES (1, 'NICOLAS MAQUIAVELO','ITALIA');
INSERT INTO AUTORES VALUES (1, 'HERMANOS GRIMM','ALEMANIA');
INSERT INTO AUTORES VALUES (1, 'POL GISE','ESPAÑA');

COMMIT;

SELECT * FROM AUTORES;

COMMIT;

CREATE TABLE SOCIO(
SOCIOS_ID NUMBER PRIMARY KEY, 
NOMBRE NVARCHAR2(30),
DIRECCION NVARCHAR2(30),
TELEFONO NVARCHAR2(10)
);

CREATE SEQUENCE SOCIO_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999
MINVALUE 1
NOCYCLE;

CREATE OR REPLACE TRIGGER INSERT_SOCIO
BEFORE INSERT ON SOCIO FOR EACH ROW BEGIN
SELECT SOCIO_SEQ.NEXTVAL INTO:NEW.SOCIO_ID FROM DUAL;
END;                       

INSERT INTO SOCIO VALUES (1, 'RICARDO','ZARAGOZA 22', '1234567890');
INSERT INTO SOCIO VALUES (1, 'ELENA','VILLA 38', '8975321890');
INSERT INTO SOCIO VALUES (1, 'ADRIÁN','MADERO 59', '2648972164');
INSERT INTO SOCIO VALUES (1, 'RITA','AVIACIÓN 94', '2764892580');
INSERT INTO SOCIO VALUES (1, 'FELIPE','ZAPATA 15', '2769321586');

SELECT * FROM SOCIO;

COMMIT;

CREATE TABLE PRESTAMO(
PRESTAMO_ID NUMBER PRIMARY KEY,
TITULO_LIBRO NVARCHAR2(30),
FECHA_PRESTAMO NVARCHAR2(12),
FECHA_DEVOLUCION NVARCHAR2(12)
);


CREATE SEQUENCE PRESTAMO_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999
MINVALUE 1
NOCYCLE;

CREATE OR REPLACE TRIGGER INSERT_PRESTAMO
BEFORE INSERT ON PRESTAMO FOR EACH ROW BEGIN
SELECT PRESTAMO_SEQ.NEXTVAL INTO:NEW.PRESTAMO_ID FROM DUAL;
END;

INSERT INTO PRESTAMO VALUES (1, 'LOS MISERABLES', '01/10/2024', '30/10/2024');
INSERT INTO PRESTAMO VALUES (1, 'EL PRINCIPITO', '15/10/2024', '30/10/2024');
INSERT INTO PRESTAMO VALUES (1, 'EL PRINCIPE', '01/09/2024', '30/09/2024');
INSERT INTO PRESTAMO VALUES (1, 'BLANCA NIEVES', '01/08/2024', '30/08/2024');
INSERT INTO PRESTAMO VALUES (1, 'HERCULES', '01/07/2024', '30/07/2024');

SELECT * FROM PRESTAMO;

COMMIT;

CREATE TABLE LIBROS_SOCIO_PRESTAMO(
LS_ID NUMBER PRIMARY KEY,
LIBROS_ID NUMBER,
SOCIOS_ID NUMBER,
PRESTAMO_ID NUMBER,
CONSTRAINT FK_LIBROS_ID_LS 
FOREIGN KEY (LIBROS_ID)
REFERENCES LIBROS (LIBROS_ID),
CONSTRAINT FK_SOCIOS_ID_TA 
FOREIGN KEY (SOCIOS_ID)
REFERENCES SOCIO (SOCIOS_ID),
CONSTRAINT FK_PRESTAMO_ID_TA 
FOREIGN KEY (PRESTAMO_ID)
REFERENCES PRESTAMO (PRESTAMO_ID)
);

SELECT * FROM LIBROS_SOCIO_PRESTAMO;

COMMIT;

INSERT INTO LIBROS_SOCIO_PRESTAMO VALUES (1,5,3,21);
INSERT INTO LIBROS_SOCIO_PRESTAMO VALUES (2,4,5,22);
INSERT INTO LIBROS_SOCIO_PRESTAMO VALUES (3,3,2,23);
INSERT INTO LIBROS_SOCIO_PRESTAMO VALUES (4,2,1,24);
INSERT INTO LIBROS_SOCIO_PRESTAMO VALUES (5,1,4,25);

COMMIT;


----------------------------------------------------------------------------------------------------------------------------------------------------
----------------------------EJERCICIO ABOGADOS--------------------------------------------


CREATE TABLE CLIENTE(
CLIENTE_ID NUMBER PRIMARY KEY, 
DNI NVARCHAR2(13),
NOMBRE NVARCHAR2(30),
DIRECCION NVARCHAR2(30),
TELEFONO NVARCHAR2(10)
);

INSERT INTO CLIENTE VALUES (1,'1234567899876','JERONIMO', 'RIO VERDE 55', '1234567899');
INSERT INTO CLIENTE VALUES (2, '2345678998761','ENRIQUETA', 'ZARAGOZA 842', '2345678991');
INSERT INTO CLIENTE VALUES (3, '3456789987612','GENARO', 'FRANCISCO VILLA 755', '3456789912');
INSERT INTO CLIENTE VALUES (4, '4567899876123','JULIA', 'EMILIANO ZAPATA 364', '4567899123');
INSERT INTO CLIENTE VALUES (5, '5678998761234','FERMIN', 'BENITO JUAREZ 823', '5678991234');

COMMIT;

CREATE TABLE ABOGADO(
ABOGADO_ID NUMBER PRIMARY KEY, 
NOMBRE NVARCHAR2(30),
DIRECCION NVARCHAR2(30),
TELEFONO NVARCHAR2(10),
HONORARIOS NUMBER (8,2)
);

INSERT INTO ABOGADO VALUES (1,'MARIO', 'MORELOS 15', '6789912345', 5314.00);
INSERT INTO ABOGADO VALUES (2, 'DULCE', '16 DE SEPTIEMBRE 322', '7899123456', 6248.91);
INSERT INTO ABOGADO VALUES (3, 'ROBERTO', '3 NORTE 315', '8991234567', 8912.82);
INSERT INTO ABOGADO VALUES (4, 'BEATRIZ', '5 DE MAYO 924', '9912345678', 4687.95);
INSERT INTO ABOGADO VALUES (5, 'JAIME', '8 ORIENTE 723', '9123456789', 4893.50);

COMMIT;

CREATE TABLE ASUNTO(
ASUNTO_ID NUMBER PRIMARY KEY,
CLIENTE_ID NUMBER,
FECHAINIC DATE,
FECHAIFIN DATE,
ESTADO NVARCHAR2(30),
CONSTRAINT FK_CLIENTE_ID_ASUNTO 
FOREIGN KEY (CLIENTE_ID)
REFERENCES CLIENTE (CLIENTE_ID)
);

ALTER TABLE ASUNTO ADD DESCRIPCION NVARCHAR2(30);

UPDATE ASUNTO SET DESCRIPCION='DIVORCIO' WHERE ASUNTO_ID=1;
UPDATE ASUNTO SET DESCRIPCION='USUCAPION' WHERE ASUNTO_ID=2;
UPDATE ASUNTO SET DESCRIPCION='INTESTADO' WHERE ASUNTO_ID=3;
UPDATE ASUNTO SET DESCRIPCION='LESIONES' WHERE ASUNTO_ID=4;
UPDATE ASUNTO SET DESCRIPCION='ROBO' WHERE ASUNTO_ID=5;

ALTER TABLE ASUNTO  ADD CONSTRAINT CHK_ESTADO 
CHECK (ESTADO IN('ARCHIVADO', 'EN TRÁMITE', 'CONCLUIDO'));

INSERT INTO ASUNTO VALUES (1, 5, '01/01/2024', '30/06/2024', 'ARCHIVADO', 3);
INSERT INTO ASUNTO VALUES (2, 4, '01/02/2024', '30/07/2024', 'EN TRÁMITE', 1);
INSERT INTO ASUNTO VALUES (3, 3, '01/03/2024', '30/08/2024', 'CONCLUIDO', 4);
INSERT INTO ASUNTO VALUES (4, 2, '01/04/2024', '30/09/2024', 'ARCHIVADO', 5);
INSERT INTO ASUNTO VALUES (5, 1, '01/05/2024', '30/10/2024', 'EN TRÁMITE', 2);


SELECT * FROM ASUNTO; 
COMMIT;


CREATE TABLE EXPEDIENTE(
EXPEDIENTE_ID NUMBER PRIMARY KEY,
CLIENTE_ID NUMBER,
ABOGADO_ID NUMBER,
ASUNTO_ID NUMBER,
CONSTRAINT FK_CLIENTE_ID_EXPEDIENTE
FOREIGN KEY (CLIENTE_ID)
REFERENCES CLIENTE (CLIENTE_ID),
CONSTRAINT FK_ABOGADO_ID_EXPEDIENTE 
FOREIGN KEY (ABOGADO_ID)
REFERENCES ABOGADO (ABOGADO_ID),
CONSTRAINT FK_ASUNTO_ID_EXPEDIENTE 
FOREIGN KEY (ASUNTO_ID)
REFERENCES ASUNTO (ASUNTO_ID)
);


INSERT INTO EXPEDIENTE VALUES (1, 4, 3, 2);
INSERT INTO EXPEDIENTE VALUES (2, 1, 5, 5);
INSERT INTO EXPEDIENTE VALUES (3, 5, 4, 1);
INSERT INTO EXPEDIENTE VALUES (4, 3, 2, 3);
INSERT INTO EXPEDIENTE VALUES (5, 2, 1, 4);

-- AGREGAR DATOS A UNA SOLA COLUMNA
UPDATE EXPEDIENTE SET ASUNTO_ID=2 WHERE EXPEDIENTE_ID=1;
UPDATE EXPEDIENTE SET ASUNTO_ID=5 WHERE EXPEDIENTE_ID=2;
UPDATE EXPEDIENTE SET ASUNTO_ID=1 WHERE EXPEDIENTE_ID=3;
UPDATE EXPEDIENTE SET ASUNTO_ID=3 WHERE EXPEDIENTE_ID=4;
UPDATE EXPEDIENTE SET ASUNTO_ID=4 WHERE EXPEDIENTE_ID=5;

ALTER TABLE EXPEDIENTE ADD ASUNTO_ID NUMBER;

ALTER TABLE EXPEDIENTE ADD CONSTRAINT FK_ASUNTO_ID_EXPEDIENTE
FOREIGN KEY (ASUNTO_ID)
REFERENCES ASUNTO (ASUNTO_ID);

INSERT INTO EXPEDIENTE (ASUNTO_ID) VALUES (2);

SELECT * FROM expediente; 
COMMIT;

-- ELIMINAR UNA COLUMNA CON DATOS, SIEMPRE Y CUANDO NO SEA FOREIGN KEY
-- Y QUE NO TENGA RESTRICCIÓN DE VALORES NOT NULL
-- ALTER TABLE PROCURADORES DROP COLUMN CEDULA;

-- EJ. DE BORRADO ACCIDENTAL DEL FAMOSO DELETE FROM
DELETE FROM ABOGADO; -- EL TENER LOS REGISTROS DE LA TABLA ABOGADO COMO LLAVE
-- FORÁNEA EN OTRA TABLA, LOS PROTEGE DE UN BORRADO ACCIDENTAL

-- EJEMPLO DE BORRADO ACCIDENTAL DE LA TABLA EXPEDIENTE
-- ESTA ES UNA ENTIDAD DÉBIL QUE SE COMPONE DE LLAVES FORÁNEAS, Y SÍ PODRÍA BORRARSE
-- DELETE FROM EXPEDIENTE;

-- CUANDO SE CONSULTA LA INFORMACIÓN LA TABLA FUE BORRADA
--SELECT * FROM EXPEDIENTE;

-- MIENTRAS NO CONFIRMEMOS EL BORRADO PERMANENTE DE LOS REGISTROS, PODEMOS
-- INSTRUIR UN ROLLBACK
-- ROLLBACK;

-- CONSULTAS DE TODOS LOS DATOS DE UNA TABLA
SELECT * FROM ABOGADO;

-- EJ. PODEMOS CONSULTAR TAMBIÉN SOLO DETERMINADAS COLUMNAS DE UNA TABLA
SELECT ABOGADO_ID, NOMBRE, TELEFONO FROM ABOGADO;

-- EJ. CONSULTAR INFORMACIÓN DE UNA TABLA DE ACUDERDO A UNA CONDICIÓN
SELECT * FROM ABOGADO WHERE ABOGADO_ID=3;

SELECT * FROM ABOGADO WHERE HONORARIOS>5000;

-- CONSULTAR INFORMACIÓN CON MÁS DE UNA CONDICIÓN CON EL OPERADOR 'AND'
SELECT * FROM ABOGADO WHERE HONORARIOS>5000 AND DIRECCION='3 NORTE 315';

-- CONSULTAR INFORMACIÓN QUE SE ENCUENTRE EN UN DETERMINADO RANGO
SELECT * FROM ABOGADO WHERE HONORARIOS BETWEEN 3000 AND 15000;

-- NO SE INTERPRETA SI PONEMOS PRIMERO EL VALOR MAYOR Y LUEGO EL MENOR
SELECT * FROM ABOGADO WHERE HONORARIOS BETWEEN 15000 AND 3000;

-- CONSULTA DE CLIENTES CUYO NOMBRE INICIA CON ALGUNA LETRA
SELECT * FROM CLIENTE WHERE NOMBRE LIKE 'J%';

-- NOS PUEDE SERVIR TAMBIÉN PARA CONSULTAR CLIENTES POR LADA TELEFÓNICA
SELECT * FROM CLIENTE WHERE TELEFONO LIKE '23%';

-- EJ. TAMBIÉN PODEMOS BUSCARLOS SI FINALIZAN CON ALGUNA LETRA O COINCIDENCIA
SELECT * FROM CLIENTE WHERE NOMBRE LIKE '%O';

SELECT * FROM CLIENTE WHERE DIRECCION LIKE 'ZARAGOZA%';

SELECT * FROM CLIENTE WHERE NOMBRE LIKE '%R%';

-- FUNCIONES DE AGRAGACIÓN
-- SELECCIONAR O CONSULTAR EL VALOR MÁXIMO DE UNA COLUMNA
SELECT MAX (HONORARIOS) FROM ABOGADO; -- ESTO NOS DEVUELVE EL MAYOR INGRESO
-- DE UN ABOGADO

-- CONSULTAR EL VALOR MÍNIMO DE UNA COLUMNA
SELECT MIN (HONORARIOS) FROM ABOGADO;

-- CONSULTAR EL PROMEDIO DE LOS VALORES DE UNA COLUMNA
SELECT AVG (HONORARIOS) FROM ABOGADO;

-- REALIZAR LA SUMATORIA DE VALORES DE UNA COLUMNA
SELECT COUNT (*), ESTADO FROM ASUNTO GROUP BY ESTADO;


-- REALIZAR UN CONTEO DE LOS REGISTROS DE UNA TABLA, LOS PODEMOS CONSULTAR
-- POR ALGUNA COLUMNA ESPECÍFICA O POR TODO 
SELECT COUNT (ABOGADO_ID) FROM ABOGADO;

SELECT COUNT (*) FROM ABOGADO;

-- PODRÍAMOS CONTAR CUANTOS ABOGADOS COBRAN MÁS DE $8000
SELECT COUNT (*) FROM ABOGADO WHERE HONORARIOS>5000;

SELECT COUNT (*) FROM ABOGADO WHERE HONORARIOS<5000;

-- EJ. PODEMOS UTILIZAR UN CONTEO PARA AGRUPAR A NUESTROS REGISTROS POR ALGÚN
-- CRITERIO. EN LA TABLA ASUNTOS AGRUPARLOS POR ESTATUS    
SELECT COUNT (*), ESTADO FROM ASUNTO GROUP BY ESTADO;

-- EJ. 2 AGRUPAR ALUMNOS POR GENERO
SELECT COUNT (*), GENERO FROM ALUMNO GROUP BY GENERO;

-- ORDENAR NUESTROS REGISTROS DE FORMA ASCENDENTE O DESCENDENTE DE ACUEDO A UN 
-- CRITERIO O COLUMNA

-- EJEMPLO ORDENAR LOS REGISTROS DE UNA TABLA DE ACUERDO A SU ID ASCENDENTE
SELECT * FROM ALUMNO ORDER  BY ALUMNO_ID;

-- EJEMPLO ORDENAR LOS REGISTROS DE UNA TABLA DE ACUERDO A SU ID DESCENDENTE
SELECT * FROM ALUMNO ORDER  BY ALUMNO_ID DESC;

-- ORDENAR MIS ALUMNOS POR ORDEN ALFABÉTICO
SELECT * FROM ALUMNO ORDER  BY NOMBRE;

-- CONTEO DE ABOGADOS QUE GANEN MÁS DE 6000 Y VER EL NOMBRE
SELECT NOMBRE, COUNT(*) AS CONTEO FROM ABOGADO WHERE HONORARIOS >6000 GROUP BY NOMBRE;

-----------------------------------------------------------------------------------------------------------------
------------------------------------CONSULTAS ANIDADAS-----------------------------------------------------------

-- Prácticamente esto es una consulta dentro de otra consulta

-- EJ. CUANDO QUEREMOS CONOCER LOS DATOS DEL ABOGADO QUE MÁS HONORARIOS COBRA
SELECT * FROM ABOGADO;

SELECT * FROM ABOGADO WHERE HONORARIOS = (SELECT MAX (HONORARIOS) FROM ABOGADO);

-- EJ2. CONOCER LOS DATOS DEL ABOGADO QUE PARTICIPA EN EL ASUNTO 3
SELECT * FROM ABOGADO WHERE ABOGADO_ID = (SELECT ABOGADO_ID FROM EXPEDIENTE WHERE ASUNTO_ID=3); -- EN UNA RELACIÓN MUCHOS A UNO SE UTILIZA EL COMPRADOR "IN" EN LUGAR DE "="

-- ESE VALOR LO PODRIAMOS OBTENER DE LA CONSULTA
SELECT * FROM EXPEDIENTE;

-- VOY A INSERTAR OTRO ABOGADO QUE PARTICIPE EN EL ASUNTO 3
INSERT INTO ABOGADO VALUES(6, 'ESTAFANIA','OAXACA, OAXACA', '3816498731', 9900.00);

INSERT INTO EXPEDIENTE  VALUES (6,3,5,3);

SELECT * FROM EXPEDIENTE;

-- PARA CUANDO NOS RETORNA MÚLTIPLES ID'S DE ABOGADO, UTILIZAMOS EL PARÁMETRO "IN"
SELECT * FROM ABOGADO WHERE ABOGADO_ID IN (SELECT ABOGADO_ID FROM EXPEDIENTE WHERE ASUNTO_ID IN 3); 

-- CONSULTAR TODA LA INFORMACIÓN DEL ABOGADO QUE PARTICIPA EN EL ASUNTO 
-- DONDE EL NOMBRE DEL CLIENTE  = 'JULIA'
-- RESOLVER POR CONSULTAS ANIDADAS

SELECT * FROM CLIENTE WHERE CLIENTE_ID = 
(SELECT CLIENTE_ID FROM CLIENTE WHERE NOMBRE = 'JULIA'); 

------------------------------------------------------------------------------------------
--------------------------CONSULTAS CON JOINS---------------------------------------------

-- Permiten unir dos o más tablas para regresar o consultar cierta información
-- unidendo las tablas por un campo que comparten en común (PK,FK)

-- INNER JOIN
-- DEVULEVE INFORMACIÓN DE UNA TABLA A Y UNA TABLA B, PERO SOLO LA INFORMACIÓN COINCIDENTE

-- EJ. UNIR LA TABLA ALUMNO CON CARRERAS_ALUMNOS A TRAVÉS DE ALUMNO_ID

SELECT * FROM ALUMNO
INNER JOIN CARRERAS_ALUMNOS
ON ALUMNO.ALUMNO_ID = CARRERAS_ALUMNOS.ALUMNO_ID;


-- OTRO EJEMPLO, UNIR CLIENTE CON ASUNTOS
SELECT * FROM CLIENTE
INNER JOIN ASUNTO
ON CLIENTE.CLIENTE_ID = ASUNTO.CLIENTE_ID;

-- LEFT JOIN 
-- PRIORIZA LA TABLA IZQUIERDA - MUESTRA TODO LO DE LA TABLA A
-- Y SOLO LO COINCIDENTE CON LA TABLA B
SELECT * FROM ALUMNO
LEFT JOIN CARRERAS_ALUMNOS
ON ALUMNO.ALUMNO_ID = CARRERAS_ALUMNOS.ALUMNO_ID;

-- RIGHT JOIN 
-- PRIORIZA LA TABLA DERECHA - MUESTRA TODO LO DE LA TABLA B
-- Y SOLO LO COINCIDENTE CON LA TABLA A
SELECT * FROM ALUMNO
RIGHT JOIN CARRERAS_ALUMNOS
ON ALUMNO.ALUMNO_ID = CARRERAS_ALUMNOS.ALUMNO_ID;

-- FULL JOIN  O OUTER JOIN 
-- MUESTRA TODO DE LA TABLA A Y DE LA TABLA B, AUNQUE NO HAYA COINCIDENCIAS
SELECT * FROM ALUMNO
FULL OUTER JOIN CARRERAS_ALUMNOS
ON ALUMNO.ALUMNO_ID = CARRERAS_ALUMNOS.ALUMNO_ID;

-- EJ. UNIR MÁS DE DOS TABLAS. ALUMNO CON CARRERAS_ALUMNOS Y CON CARRERAS
SELECT * FROM ALUMNO
INNER JOIN CARRERAS_ALUMNOS
ON ALUMNO.ALUMNO_ID = CARRERAS_ALUMNOS.ALUMNO_ID
INNER JOIN CARRERAS
ON CARRERAS.CARRERA_ID = CARRERAS_ALUMNOS.CARRERA_ID;

-- PODEMOS SOLICITAR SOLO CIERTAS COLUMNAS UNA VEZ FUNCIONA EL JOIN
SELECT ALUMNO.ALUMNO_ID, ALUMNO.NOMBRE, ALUMNO.GRADO, CARRERAS.NOMBRE FROM ALUMNO
INNER JOIN CARRERAS_ALUMNOS
ON ALUMNO.ALUMNO_ID = CARRERAS_ALUMNOS.ALUMNO_ID
INNER JOIN CARRERAS
ON CARRERAS.CARRERA_ID = CARRERAS_ALUMNOS.CARRERA_ID;

-- CREAR LA CONSULTA IDENTIFICANDO A NUESTRAS TABLAS CON UN ALIAS
SELECT A.ALUMNO_ID, A.NOMBRE, A.GRADO, C.NOMBRE FROM ALUMNO A
INNER JOIN CARRERAS_ALUMNOS CA
ON A.ALUMNO_ID = CA.ALUMNO_ID
INNER JOIN CARRERAS C
ON C.CARRERA_ID = CA.CARRERA_ID;

-- AGREGAR UN ALIAS PARA MOSTRAR EN LOS ENCABEZADOS DE LAS COLUMNAS DE LA CONSULTA
SELECT A.ALUMNO_ID AS MATRICULA, A.NOMBRE AS ALUMNO, A.GRADO AS SEMESTRE, C.NOMBRE AS CARRERA FROM ALUMNO A
INNER JOIN CARRERAS_ALUMNOS CA
ON A.ALUMNO_ID = CA.ALUMNO_ID
INNER JOIN CARRERAS C
ON C.CARRERA_ID = CA.CARRERA_ID;

-- CONSULTAR TODA LA INFORMACIÓN DEL ABOGADO QUE PARTICIPA EN EL ASUNTO 
-- DONDE EL NOMBRE DEL CLIENTE  = 'JULIA'
-- RESOLVER CON INNER JOIN O EL JOIN QUE GUSTEN
SELECT AB.ABOGADO_ID, AB.NOMBRE, AB.DIRECCION, AB.TELEFONO, AB.HONORARIOS, C.NOMBRE FROM ABOGADO AB
INNER JOIN EXPEDIENTE E
ON AB.ABOGADO_ID = E.ABOGADO_ID
INNER JOIN ASUNTO A
ON A.ASUNTO_ID = E.ASUNTO_ID
INNER JOIN CLIENTE C
ON C.CLIENTE_ID = A.ASUNTO_ID
WHERE C.NOMBRE = 'GENARO';

    
    