CREATE TABLE TUTORES (
TUTOR_ID NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(50),
EMAIL NVARCHAR2(100),
CLAVE CHAR(4) CHECK (CLAVE IN('A','B','C','D'))
);

-- INSERTAR REGISTROS EN LA TABLA TUTORES
INSERT INTO TUTORES 
VALUES(1, 'TEREZA LA MALA', 'TEREZALAMALA@CORREO.COM', 'A');

INSERT INTO TUTORES 
VALUES(2, 'TOMAS TREJO', 'TOMAS@CORREO.COM', 'B');

INSERT INTO TUTORES 
VALUES(3, 'FERRER DIAZ', 'FERRER@CORREO.COM', 'C');

INSERT INTO TUTORES 
VALUES(4, 'ANA LARA', 'ANA@CORREO.COM', 'D');

INSERT INTO TUTORES 
VALUES(5, 'JOSE MORALES', 'JOSEMORA@CORREO.COM', 'A');


-- CREANDO LA TABLA TUTOTRES_ALUMNOS
CREATE TABLE TUTORES_ALUMNOS(
TUTORALUM_ID NUMBER PRIMARY KEY,
TUTOR_ID NUMBER,
ALUMNO_ID NUMBER,
CONSTRAINT FK_TUTOR FOREIGN KEY (TUTOR_ID) REFERENCES TUTORES(TUTOR_ID),
CONSTRAINT FK_ALUMNO FOREIGN KEY (ALUMNO_ID) REFERENCES ALUMNO(ALUMNO_ID)
);

--INSERTANDO CONTENIDO A LA TABLA TUTORES_ALUMNOS
INSERT INTO TUTORES_ALUMNOS VALUES(1,3,1);
INSERT INTO TUTORES_ALUMNOS VALUES(2,5,3);
INSERT INTO TUTORES_ALUMNOS VALUES(3,1,2);

-- CREAANDO LA TABLA STATUS_ALUMNOS
CREATE TABLE STATUS_ALUMNOS(
STATUS_ID NUMBER PRIMARY KEY,
DESCRIPCION NVARCHAR2(100)
CHECK (DESCRIPCION IN('ALUMNO INSCRITO','ALUMNO NO INSCRITO'))
);

-- INSERTAR LOS REGISTROS EN LA TABLA STATUS_ALUMNOS
INSERT INTO STATUS_ALUMNOS VALUES(0,'ALUMNO NO INSCRITO');
INSERT INTO STATUS_ALUMNOS VALUES(1,'ALUMNO INSCRITO');

--AGREGAR LA REFERENCIA DE LA LLAVE FORANEA EN LA TABLA ALUMNO HACIA STATUS_ALUMNOS
ALTER TABLE ALUMNO ADD CONSTRAINT FK_STATUS FOREIGN KEY(STATUS)
REFERENCES STATUS_ALUMNOS(STATUS_ID);


INSERT INTO ALUMNO 
VALUES(4, 'MARIANA', '11/03/1993', 'FEMENINO', '1ER SEMESTRE', 'CDMX',1);

COMMIT;







