-- comentarios de una sola linea
-- comentarios de una linea con dos signos medidos seguidos--
/*
comentarios de 
multiples lineas

*/
-- SQL (lenguaje de consulta estructuradi)
--base de datos relacionales
--conjunto fde datos relacionados entre si y que son alamcenadas entre si

--toda tabla deve llevar llave primaria 
--primary key es un identificador unico 
--puede llevar llave foreana Foreing key
--la llave foranea es la llave primaria que provienen de otra tabla 
--Columnas con susu diferentes tiopos de datos

--tipos de datos oracle
--NUMBER permiter almacenar datos numericos enteros y decimales 
--varChar - varchar2 este ultimo permite datos alfanumericos
--y caracteres especiales y ademas optimiza la memoria
--DATE para manejo de fecha y hora

--control + s para guardar nuestro script SQL
-- vamos a crear la primera tabla de ejemplo para aguardar 
--la info de alumnos 
--sintaxis para crear una tabla es la siguiente

/*
CREATE TABLA nombreTabla (
nombreColumnas topoDato
columna 2 tipoDatos
.
.
);
*/

--ALUMNOS
--MATRICULA DEL ALUMNO O ID
--NOMBRE
--FECHA DE NACIMIENTO
--GENERO
--GRADO
--CIUDAD
--STATUS -- ESTE SERA NUMERICO PARAR SABER SI EL ALUMNO ESTA INSCRITO
-- INSCRITO (1)  O NO  (0)

--se recomienda que las sentencias sql se escriban con mayusculas
CREATE TABLE ALUMNO (
ALUMNO_ID NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(30),
FECHANAC DATE,
GENERO NVARCHAR2(18),
GRADO NVARCHAR2(30),
CIUDAD NVARCHAR2(30),
STATUS NUMBER
);

-- ver la estructura de una tabla 
DESCRIBE alumno;

--como podemos renombrar una tabla por si nos equivocamos               
ALTER TABLE ALUMNO RENAME TO ALUMNOS;

-- ELIMINAR UNA TABLA CON TODO SU CONTENIDO
DROP TABLE ALUMNOS;

-- CREANDO TABLA CARRERAS
CREATE TABLE CARRERAS(
CARRERA_ID NUMBER PRIMARY KEY DISABLE,
NOMBRE NVARCHAR2(30),
AREA NVARCHAR2(30),
DURACION NVARCHAR2(30)
);

-- COMO PODEMOS RENOMBRAR UNA COLUMNA DE UNA TABLA
ALTER TABLE CARRERAS RENAME COLUMN DURACION TO SEMESTRES;

-- COMO AGREGAR UNA COLUMNA A UNA TABLA EXISTENTE
--DELIMITADO NUMBER, 8 POSICIONES NUMERICAS Y DE ELLAS DOS SON DECIMALES 
ALTER TABLE CARRERAS ADD PRESUPUESTO NUMBER(8,2);

DESCRIBE CARRERAS;

--MODIFICAR EL TIPO DE DATO DE UNA COLUMNA SIEMPRE Y CUANDO NO TENGA DATOS
--SI TIENEN DATOS NO SERA POSIBLE
ALTER TABLE CARRERAS MODIFY SEMESTRES NUMBER;

--CAMBIANDO EL TIPO DE DATO DE RETORNO 
ALTER TABLE CARRERAS MODIFY SEMESTRES NVARCHAR2(50);

--CREAR UNA TERCER TABLA RELACIONAL PARA TENER UNA CARDINALIDADA DE UNO A MUCHOS
-- ES DECIR 

CREATE TABLE CARRERAS_ALUMNOS(
CA_ID NUMBER PRIMARY KEY,
ALUMNO_ID NUMBER,
CARRERA_ID NUMBER
);

DESCRIBE CARRERAS_ALUMNOS;

--CREASION DE RESTRICCIONES NOS VA PERMITIR INTRODUCIR
--DETERMINADOS VALORES EN NUESTRAS COLUMNAS

--RESTRICCIONES DE TIPO CHECK VALIDAN O VERIFICAN UN VALOR
--EN LA TABLA ALUMNOS VAMOS A CREAR UNA RESTRICCION PARA QUE EN LA COMUNA GENERO SOLO 
--PODAMOS INSERTAR EL GENERO MASCULINO O FEMENINO

ALTER TABLE ALUMNO ADD CONSTRAINT CHK_GENERO
CHECK (GENERO IN('MASCULINO', 'FEMENINO'));

--LAS LLAVES PRIMARIAS EN SI SON UNA RESTRICCION ES DECIR LOS VALORES 
--ID SON UNICOS 
--RESTRICCIONES INIQUE
--SIRVEN PARA EVITARB QUE UN VALOR QUE NO SEA LLAVE PRIMARIA SE REPITAN 
--EN ESTE CASO CARRERAS

ALTER TABLE CARRERAS ADD  CONSTRAINT UNQ_NOMBRE_CARRERAS
UNIQUE (NOMBRE);

--COMO PODRIAMOS ELIMIAR UNA RESTRICCION
ALTER TABLE CARRERAS DROP CONSTRAINT UNQ_NOMBRE_CARRERAS;
 
-- RESTICCION DE LLAVES FORANEAS LAS CUALES ESTABLECEN LA RELACION 
-- DE LA INFORMACION EN OTRAS TABLAS MEDIANTE LAS LLAVES PRIMARIAS 
--ESTO HACE QUE LOS DATOS EN LAS TABLAS RELACIONALES DEPENDAN DE LA EXISTENCIA PREVIA
--EN LAS OTRAS TABLAS

-- EJEMPLO CREANDO LAS LLAVES FORANEAS EN LA TABLA CARRERAS_ALUMNOS 
--PRIMERO EN LA LLAVE FORANEA RECIVE LA INFO DEL ALUMNO 

--NOMBRE DE LA TABLA
ALTER TABLE CARRERAS_ALUMNOS ADD CONSTRAINT FK_ALUMNO_ID_CA -- NOMBRE DE LA RESTICCION
FOREIGN KEY (ALUMNO_ID) --EN QUE PARTE DE LA TABLA BAMOS A RECIBIR
REFERENCES ALUMNO (ALUMNO_ID); 

--
ALTER TABLE CARRERAS_ALUMNOS ADD CONSTRAINT FK_CARRERA_ID_CA 
FOREIGN KEY (CARRERA_ID) 
REFERENCES CARRERAS (CARRERA_ID); 

--ejercicio tutores y tutores_alumnos y status_alumnos














