-- LA CREACION DE SECUENCIAS 
-- LAS SECUENCIAS SON OBJETOS QUE NOS PERMITEN GENERAR VALORES DE NUEMEROS ENTEROS 
--EN FORMA CONSECUTIVA CON UN INCREMENTO DETERMINADO
--NOA VA APERMITIR DETERMINAR LA CANTIDAD DE INCREMENTO
--SE UTILIZAN PARA GENERAR LAS LLAVES PRIMARIAS Y DE ESTA FORMA LOGRAMOS AUN 
--MAS QUE LOS VALORES NO SE REPITAN 
--VAMOS ACREAR IUNA CESUENSIA PARA UNA TABLA QUE YA TIENE REGISTROS INCERTADOS 
--CREA UNA SECIENCIA CON VALORES DEFINIDOS 
SELECT * FROM ALUMNO;

CREATE SEQUENCE ALUMNO_SEQ --NOMBRE DE LA SECUENCIA
START WITH 5 --DESDE QUE VALOR INICIA
INCREMENT BY 1 -- EN CUANTO EN CUANTO INCREMENTA
MAXVALUE 999 --VALOR MAXIMO
MINVALUE 1 --VALOR MINIMO
NOCYCLE; --SI QUEREMOS QUEREMOS QUE SE SICLE SERIA CON CYCLE

-- EJEMPLO DE CREAR UNA SECUENCIA CON VALORES DEFAULT
--LA CUAL ES UTIL PARA TABLAS QUE NO TIENE DATOS AGREGADOS
CREATE SEQUENCE COMPRAS_SEQ;
COMMIT;

--VAMOS A CREAR EL DISPARADOR O DE TRIGGERS
--ESTOS SON UN TIPO DE PROCEDIMIENTO ALMACENADO QUE DESENCADENA UN EVENTO 
--EN ESTE CASO LO UTILIZAREMOS PARA INCERTAR LAS LLAVES PRIMARIAS 
--EJEMPO. CREACION DE L DISPARADOR PARA INCERTAR LOS IDS EN LA TABLA ALUMNO

CREATE OR REPLACE TRIGGER INSERT_ALUMNO -- NOMBRE DEL TRIGGER
BEFORE INSERT ON ALUMNO FOR EACH ROW BEGIN -- DONDE ACTUARA
SELECT ALUMNO_SEQ.NEXTVAL INTO:NEW.ALUMNO_ID FROM DUAL; -- QUE HACE TOMA EL VALOR DE LA SECUENCIA PARA INCERTARLO PARA TOMAR EL VALOR DEL ID
END;

--EJ. INSERTAR UN NUEVO ALUMNO, PERO EXPERIMENTANDO 
--COMO EL TRIGGER YA HACE LA INSERCION DEL ID POR NOSOTROS

INSERT INTO ALUMNO 
VALUES(3, 'CARMEN TAPIA', '12/05/2002', 'FEMENINO', '1ER SEMESTRE', 'CHIAPAS',0);

COMMIT;

--PUEDO OMITIR EL ID INDICANDO QUE COLUMNAS VOR A INCERTAR UNICAMENTE

INSERT INTO ALUMNO (NOMBRE, FECHANAC, GENERO, GRADO, CIUDAD, STATUS) VALUES
('JUAN PEREA', '12/12/1990', 'MASCULINO', '4TO SEMESTRE', 'SAN LUIS',1);

SELECT * FROM ALUMNO;
COMMIT;

--COMO ELIMINAR UN REGISTRO DE UNA TABLA CASI SIEMPRE ES RECOMENDABLE IDENTIFICAR A NUESTRO REGISTRO 
--A ELIMINAR POR OD

DELETE  FROM ALUMNO WHERE ALUMNO_ID=6;

--EJ. INTENTAR BORRAR EL REGISTR 1 QUE YA TIENE UNA CARRERA ASIGNADA Y TUTOR
DELETE  FROM ALUMNO WHERE ALUMNO_ID=1;

-- si QUEREMOS RECUPERAR UN REGISTRO ELIMINADO O UNA ACTUALIZACION HAY UNA 
--INSTRUCCION QUE NOS LLEBA AL AESTADO DE NUESTRO ULTIMO COMMIT
ROLLBACK;
COMMIT;

--PODEMOS EDITAR LA SECUENCIA SI QUEREMOS RECUPERAR EL CINSECUTIVO DE NUMEROS
--LO HACEMOS DE SDE EL PANEL DE CONEXION EN EL APARTADO DE SECUENCIA

-- COMO ACTUALIZAR VALORES DE UN REGISTRO
--EJ. VAMOS A EDITAR DE ALMA LA CIUDAD
UPDATE ALUMNO SET CIUDAD = 'MONTERREY' WHERE alumno_id=5;
--CONFIRMAMOS EL CAMBIO CON UN COMMIT
COMMIT;

--EJEMPLO DE ACTUALIZACION DE VARIOS VALORES AL MISMO TIEMPO
UPDATE ALUMNO SET CIUDAD = 'MONTERREY', GRADO = '5TO SEMESTRE', STATUS =1 WHERE alumno_id=5;
SELECT * FROM ALUMNO;
COMMIT;

-- VAMOS A VER QUE OCURRE SI CREO UNA SECUENCIA CON VALORES POR DEFECTO 
--ES DECIR QUE INICIE DESDE EL UNO Y CREO TAMBIEN UN DISPARADOR 
CREATE SEQUENCE CARRERAS_SEQ;

SELECT * FROM CARRERAS;

--CREAR EL TRIGGER PARA LA TABLA CARRERAS
CREATE OR REPLACE TRIGGER INSERT_CARRERAS -- NOMBRE DEL TRIGGER
BEFORE INSERT ON CARRERAS FOR EACH ROW BEGIN -- DONDE ACTUARA
SELECT CARRERAS_SEQ.NEXTVAL INTO:NEW.CARRERA_ID FROM DUAL; -- QUE HACE TOMA EL VALOR DE LA SECUENCIA PARA INCERTARLO PARA TOMAR EL VALOR DEL ID
END;

-- INTENTAMOS INCERTAR UNA CARRERA EL DISPARADOR LO INTENTRA INCERTAR CON EL ID1
--HACI QUE TENDREMOS QUE LLEGAR AL VALOR HASTA QUE SEA EL CORRECTO
DELETE  FROM CARRERAS WHERE CARRERA_ID=21;
INSERT INTO CARRERAS VALUES(5, 'FICICA','EXACTAS', '10 SEMESTRES', 210000.80);
UPDATE CARRERAS SET AREA = 'ECONOMIAS' WHERE carrera_id=4;

SELECT * FROM CARRERAS;
COMMIT;

-------------------------------------------------------------------------------------------
--------------------------EJERSICIO BIBLIOTECA---------------------------------------------
-------------------------------------------------------------------------------------------
CREATE TABLE AUTOR(
ID_AUTOR NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(50),
NACIONALIDAD NVARCHAR2(50)
);

SELECT * FROM AUTOR;
-- INSERTAR REGISTROS A LA TABLA AUTOR
INSERT INTO AUTOR (ID_AUTOR, NOMBRE, NACIONALIDAD) VALUES (1, 'GABRIEL GARCIA MARQUEZ', 'COLOMBIA');
INSERT INTO AUTOR (ID_AUTOR, NOMBRE, NACIONALIDAD) VALUES (2, 'MARIO VARGAS LLOSA', 'PERÚ');
INSERT INTO AUTOR (ID_AUTOR, NOMBRE, NACIONALIDAD) VALUES (3, 'ISABEL ALLENDE', 'CHILE');
INSERT INTO AUTOR (ID_AUTOR, NOMBRE, NACIONALIDAD) VALUES (4, 'JORGE LUIS BORGES', 'ARGENTINA');
INSERT INTO AUTOR (ID_AUTOR, NOMBRE, NACIONALIDAD) VALUES (5, 'JULIO CORTÁZAR', 'ARGENTINA');
INSERT INTO AUTOR (ID_AUTOR, NOMBRE, NACIONALIDAD) VALUES (6, 'PABLO NERUDA', 'CHILE');


CREATE TABLE LIBRO(
ID_LIBRO NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(50),
ID_AUTOR NUMBER,
CANT_COPIAS NUMBER CHECK(CANT_COPIAS >0),
CONSTRAINT FK_AUTOR FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR(ID_AUTOR)
);

SELECT * FROM LIBRO;
-- INSERTAR REGISTROS A LA TABLA LIBRO
INSERT INTO LIBRO (ID_LIBRO, NOMBRE, ID_AUTOR, CANT_COPIAS) VALUES (1, 'CIEN AÑOS DE SOLEDAD', 1, 5);
INSERT INTO LIBRO (ID_LIBRO, NOMBRE, ID_AUTOR, CANT_COPIAS) VALUES (2, 'LA CASA VERDE', 2, 3);
INSERT INTO LIBRO (ID_LIBRO, NOMBRE, ID_AUTOR, CANT_COPIAS) VALUES (3, 'LA SOMBRA DEL VIENTO', 3, 7);
INSERT INTO LIBRO (ID_LIBRO, NOMBRE, ID_AUTOR, CANT_COPIAS) VALUES (4, 'EL ALEPH', 4, 2);
INSERT INTO LIBRO (ID_LIBRO, NOMBRE, ID_AUTOR, CANT_COPIAS) VALUES (5, 'RAYUELA', 5, 4);

CREATE TABLE SOCIO(
ID_SOCIO NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(50),
DIRECCION NVARCHAR2(100),
TELEFONO NVARCHAR2(10)
);

SELECT * FROM SOCIO;
-- INSERTAR REGISTROS A LA TABLA SOCIO
INSERT INTO SOCIO (ID_SOCIO, NOMBRE, DIRECCION, TELEFONO) VALUES (1, 'JUAN PEREZ', 'CALLE FALSA 123, CDMX', '5512345678');
INSERT INTO SOCIO (ID_SOCIO, NOMBRE, DIRECCION, TELEFONO) VALUES (2, 'MARIA LOPEZ', 'AVENIDA CENTRAL 45, BOGOTÁ', '5719876543');
INSERT INTO SOCIO (ID_SOCIO, NOMBRE, DIRECCION, TELEFONO) VALUES (3, 'CARLOS RAMIREZ', 'CALLE SUR 6, LIMA', '5198765432');
INSERT INTO SOCIO (ID_SOCIO, NOMBRE, DIRECCION, TELEFONO) VALUES (4, 'ANA MARTINEZ', 'PASEO DE LA REFORMA, CDMX', '5587654321');
INSERT INTO SOCIO (ID_SOCIO, NOMBRE, DIRECCION, TELEFONO) VALUES (5, 'PEDRO GARCÍA', 'CARRERA 7, MEDELLÍN', '5741234567');

CREATE TABLE PRESTAMO(
ID_PRESTAMO NUMBER PRIMARY KEY,
ID_SOCIO NUMBER,
ID_LIBRO NUMBER,
FECHA_PRESTAMO DATE,
FECHA_DEVOLUCION DATE,
CONSTRAINT FK_SOCIO FOREIGN KEY (ID_SOCIO) REFERENCES SOCIO(ID_SOCIO),
CONSTRAINT FK_LIBRO FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO(ID_LIBRO),
CONSTRAINT CHK_FECHA CHECK (FECHA_DEVOLUCION >= FECHA_PRESTAMO)
);

SELECT * FROM PRESTAMO;
-- INSERTAR REGISTROS A LA TABLA PRESTAMO
INSERT INTO PRESTAMO VALUES (1, 1, 1, '15/09/2023', '15/10/2023');
INSERT INTO PRESTAMO VALUES (2, 2, 2, '08/06/2023', '08/07/2023');
INSERT INTO PRESTAMO VALUES (3, 3, 3, '12/01/2023', '12/02/2023');
INSERT INTO PRESTAMO VALUES (4, 4, 4, '05/08/2023', '05/08/2023');
INSERT INTO PRESTAMO VALUES (5, 5, 5, '12/12/2023', '12/01/2024');

-- INDICAR INDICE PARA EVITAR MULTIPLES PRESTAMOS DEL MISMO LIBRO AL MISMO SOCIO
CREATE UNIQUE INDEX IDX_PRESTAMO_UNICO
ON PRESTAMO(ID_SOCIO, ID_LIBRO, FECHA_PRESTAMO);

-- SECUENCIA PARA LA TABLA AUTOR
CREATE SEQUENCE SEQ_AUTOR START WITH 1 INCREMENT BY 1;

--ELIMINO SECUENCIA
DROP SEQUENCE SEQ_AUTOR;
-- LA VUELVO ACREAR
CREATE SEQUENCE SEQ_AUTOR START WITH 7 INCREMENT BY 1;

--TRIGGER PARA LA TABLA AUTOR
CREATE OR REPLACE TRIGGER TRG_AUTOR_AUTOINCREMENT
BEFORE INSERT ON AUTOR
FOR EACH ROW
BEGIN
    IF :NEW.ID_AUTOR IS NULL THEN
        SELECT SEQ_AUTOR.NEXTVAL INTO :NEW.ID_AUTOR FROM DUAL;
    END IF;
END;
--AGREGAR REGISTRO EN LA TABLA AUTOR
INSERT INTO AUTOR (NOMBRE, NACIONALIDAD) VALUES ('CARLOS FUENTES', 'MÉXICO');
INSERT INTO AUTOR (NOMBRE, NACIONALIDAD) VALUES ('JUAN RULFO', 'MÉXICO');

SELECT * FROM AUTOR;

COMMIT;

-- ALTERE LA TABLA AUTOR POR UN VALOR NO DEFINIDO CORRECTAMENTE
ALTER TABLE AUTOR
MODIFY (NACIONALIDAD NVARCHAR2(50));

-- CEAR TODOS LAS SECUENCIAS RESTANTES DE LAS TABLAS 
CREATE SEQUENCE SEQ_LIBRO START WITH 6 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SOCIO START WITH 6 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRESTAMO START WITH 6 INCREMENT BY 1;

-- CREAR TRIGGER DE LA TABLA LIBRO
CREATE OR REPLACE TRIGGER TRG_LIBRO_AUTOINCREMENT
BEFORE INSERT ON LIBRO
FOR EACH ROW
BEGIN
    IF :NEW.ID_LIBRO IS NULL THEN
        SELECT SEQ_LIBRO.NEXTVAL INTO :NEW.ID_LIBRO FROM DUAL;
    END IF;
END;
 -- INGRESAR UN NUEVO REGISTRO CON EL TRIGGER ACTIVO DE LA TABLA LIBRO
 INSERT INTO LIBRO (NOMBRE, ID_AUTOR, CANT_COPIAS) VALUES ('VEINTE POEMAS DE AMOR', 6, 10);

-- CREAR TRIGGER DE LA TABLA SOCIO
CREATE OR REPLACE TRIGGER TRG_SOCIO_AUTOINCREMENT
BEFORE INSERT ON SOCIO
FOR EACH ROW
BEGIN
    IF :NEW.ID_SOCIO IS NULL THEN
        SELECT SEQ_SOCIO.NEXTVAL INTO :NEW.ID_SOCIO FROM DUAL;
    END IF;
END;
 -- INGRESAR UN NUEVO REGISTRO CON EL TRIGGER ACTIVO DE LA TABLA SOCIO
 INSERT INTO SOCIO (NOMBRE, DIRECCION, TELEFONO) VALUES ('LAURA FERNANDEZ', 'CALLE NORTE 34, QUITO', '5935432167');

-- CREAR TRIGGER DE LA TABLA PRESTAMO
CREATE OR REPLACE TRIGGER TRG_PRESTAMO_AUTOINCREMENT
BEFORE INSERT ON PRESTAMO
FOR EACH ROW
BEGIN
    IF :NEW.ID_PRESTAMO IS NULL THEN
        SELECT SEQ_PRESTAMO.NEXTVAL INTO :NEW.ID_PRESTAMO FROM DUAL;
    END IF;
END;
 -- INGRESAR UN NUEVO REGISTRO CON EL TRIGGER ACTIVO DE LA TABLA PRESTAMO
INSERT INTO PRESTAMO (ID_SOCIO, ID_LIBRO, FECHA_PRESTAMO, FECHA_DEVOLUCION) 
VALUES (2, 1, '12/01/2023', '12/02/2024');
INSERT INTO PRESTAMO (ID_SOCIO, ID_LIBRO, FECHA_PRESTAMO, FECHA_DEVOLUCION) 
VALUES (5, 3, '20/01/2023', '20/02/2024');

SELECT * FROM PRESTAMO;
COMMIT;

-- ELIMINANDO LAS TABLAS PARA RESTABLECER SUS VALORES
DROP TABLE AUTOR CASCADE CONSTRAINTS;
DROP TABLE LIBRO CASCADE CONSTRAINTS;
DROP TABLE SOCIO CASCADE CONSTRAINTS;
DROP TABLE PRESTAMO CASCADE CONSTRAINTS;


