------------CASO ASUNTO PROCURADURIA-----------------
-----------------------------------------------------

--CREAR TABLA CLIENTE
CREATE TABLE CLIENTE(
ID_CLIENTE NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(50),
DIRECCION NVARCHAR2(100),
TELEFONO NVARCHAR2(10)
);

SELECT * FROM CLIENTE;

-- CREAR LA SECEUNCIA Y DISPARADOR TRIGGER
CREATE SEQUENCE SEQ_CLIENTE START WITH 1 INCREMENT BY 1;

-- CREAR TRIGGER DE LA TABLA CLIENTE
CREATE OR REPLACE TRIGGER TRG_CLIENTE_AUTOINCREMENT
BEFORE INSERT ON CLIENTE
FOR EACH ROW
BEGIN
    IF :NEW.ID_CLIENTE IS NULL THEN
        SELECT SEQ_CLIENTE.NEXTVAL INTO :NEW.ID_CLIENTE FROM DUAL;
    END IF;
END;

-- INGRESAR REGISTROS A LA TABLA CLIENTE 
INSERT INTO CLIENTE VALUES ('1', 'FERNANDO TORRES', 'CALLE PALOMAS MEXICO', '1234567890');
INSERT INTO CLIENTE VALUES ('2', 'KARLA MORA LUNA', 'CALLE PALOMAS TOLUCA', '1212121212');
INSERT INTO CLIENTE VALUES ('3', 'MARTHA SANCHEZ', 'VERACRUZ', '1313131313');
INSERT INTO CLIENTE VALUES ('4', 'MARIO LARA', 'OAXACA', '1414141414');
INSERT INTO CLIENTE VALUES ('5', 'ARTURO MEDINA', 'CHIAPAS', '1515151515');
INSERT INTO CLIENTE VALUES ('7', 'MARIO MEDINA', 'CHIAPAS', '1515150015');


--CREAR TABLA ASUNTO
CREATE TABLE ASUNTO(
ID_ASUNTO NUMBER PRIMARY KEY,
ESTADO NVARCHAR2(50),
FECHA_INICIO DATE,
FECHA_FINALIZADA DATE,
ID_CLIENTE NUMBER,
CONSTRAINT FK_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

SELECT * FROM ASUNTO;

-- CREAR LA SECEUNCIA Y DISPARADOR TRIGGER
CREATE SEQUENCE SEQ_ASUNTO START WITH 1 INCREMENT BY 1;

-- CREAR TRIGGER DE LA TABLA ASUNTO
CREATE OR REPLACE TRIGGER TRG_ASUNTO_AUTOINCREMENT
BEFORE INSERT ON ASUNTO
FOR EACH ROW
BEGIN
    IF :NEW.ID_ASUNTO IS NULL THEN
        SELECT SEQ_ASUNTO.NEXTVAL INTO :NEW.ID_ASUNTO FROM DUAL;
    END IF;
END;

-- INGRESAR REGISTROS A LA TABLA ASUNTO 
INSERT INTO ASUNTO VALUES ('1', 'EN PROCESO PRIMERA FACE', '10/06/2023', '10/05/2025','1');
INSERT INTO ASUNTO VALUES ('2', 'TERMINADO', '05/06/2022', '11/05/2024','3');
INSERT INTO ASUNTO VALUES ('3', 'TERMINADO', '01/01/2020', '15/07/2024','5');
INSERT INTO ASUNTO VALUES ('4', 'EN PROCESO DE FINALIZACION', '10/06/2020', '','2');
INSERT INTO ASUNTO VALUES ('5', 'EN PROCESO', '25/10/2019', '','4');

-- CREAR TABLA PROCURADOR
CREATE TABLE PROCURADOR(
ID_PROCURADOR NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(50),
DIRECCION NVARCHAR2(50),
TELEFONO NVARCHAR2(10),
HONORARIOS NUMBER(8,2)
);

SELECT * FROM PROCURADOR;

-- CREAR LA SECEUNCIA Y DISPARADOR TRIGGER
CREATE SEQUENCE SEQ_PROCURADOR START WITH 1 INCREMENT BY 1;

-- CREAR TRIGGER DE LA TABLA PROCURADOR
CREATE OR REPLACE TRIGGER TRG_PROCURADOR_AUTOINCREMENT
BEFORE INSERT ON PROCURADOR
FOR EACH ROW
BEGIN
    IF :NEW.ID_PROCURADOR IS NULL THEN
        SELECT SEQ_PROCURADOR.NEXTVAL INTO :NEW.ID_PROCURADOR FROM DUAL;
    END IF;
END;

-- INGRESAR REGISTROS A LA TABLA PROCURADOR 
INSERT INTO PROCURADOR VALUES ('1', 'TOMAS MCLAREN', 'AV. LAS TORRES TOLUCA', '1234567890',10000.00);
INSERT INTO PROCURADOR VALUES ('2', 'SARA ROJAS', 'CDMX', '5555555555',20000.00);
INSERT INTO PROCURADOR VALUES ('3', 'ADRIANA MENDEZ', 'NUEVO LEON GUANAJUATO', '4444444444',30000.00);
INSERT INTO PROCURADOR VALUES ('4', 'JOSE DEL JESUS', 'SAN LUIS POTOSI', '6666666666',15000.00);
INSERT INTO PROCURADOR VALUES ('5', 'JORGE ANDRADE', 'AV. LAS TORRES TOLUCA', '1234567890',10000.00);


--CREAR TABLA ASUNTO_PROCURADOR
CREATE TABLE ASUNTO_PROCURADOR(
ID_AP NUMBER PRIMARY KEY,
ID_PROCURADOR NUMBER,
ID_ASUNTO NUMBER,
CONSTRAINT FK_PROCURADOR FOREIGN KEY (ID_PROCURADOR) REFERENCES PROCURADOR(ID_PROCURADOR),
CONSTRAINT FK_ASUNTO FOREIGN KEY (ID_ASUNTO) REFERENCES ASUNTO(ID_ASUNTO)
);

SELECT * FROM ASUNTO_PROCURADOR;

-- CREAR LA SECEUNCIA Y DISPARADOR TRIGGER
CREATE SEQUENCE SEQ_AP START WITH 1 INCREMENT BY 1;

-- CREAR TRIGGER DE LA TABLA ASUNRO_PROCURADOR
CREATE OR REPLACE TRIGGER TRG_AP_AUTOINCREMENT
BEFORE INSERT ON ASUNTO_PROCURADOR
FOR EACH ROW
BEGIN
    IF :NEW.ID_AP IS NULL THEN
        SELECT SEQ_AP.NEXTVAL INTO :NEW.ID_AP FROM DUAL;
    END IF;
END;

-- INGRESAR REGISTROS A LA TABLA ASUNTO_PROCURADOR 
INSERT INTO ASUNTO_PROCURADOR VALUES ('1', '1', '1');
INSERT INTO ASUNTO_PROCURADOR VALUES ('2', '5', '5');
INSERT INTO ASUNTO_PROCURADOR VALUES ('3', '2', '2');
INSERT INTO ASUNTO_PROCURADOR VALUES ('4', '1', '3');
INSERT INTO ASUNTO_PROCURADOR VALUES ('5', '3', '4');
commit;

-- COMO ELIMIAR UNA COLUMNA CO DATOS 
-- QUE NO TENGA RESTRICCION 
-- ALTER TABLE PROCURADORES DROP COLUM CEDULA

--RJ BORAR ACCIDENTALMENTE 
DELETE FROM PROCURADOR;

--EL TENER EL REGISTRO DE LOS PROCURADORES O LLAVE FORANEA DE OTRA TABLA 
--LOS PROTEGE DE UN BORRADO ACCIDENTAL

--EJEMPLO DE BORRADO ACCIDENTAL DE LA TABLA ASUNTOS_PROCURADORES
--ESTA ES UNA ENTIDAD DEVIL QUE SE COMPONE DE LLAVES FORANEAS
DELETE FROM asunto_procurador;

--PARA RECUPERAR LOS ARCHIVOS ELIMINADOS ES CON EL SIGUIENTE COMANDO
--MIENTRAS NO CONFIRMEMOS EL BORRADO PERMANENTE DE LOS REGISTRO PODEMOS
-- INSTRUIR UN ROLLBACK; 
ROLLBACK;

-- CONSULTAS DE TODOS LOS DATOS DE UNA TABLA QUE SE REALIZA CON LA SENTENCIA SELCT
SELECT * FROM PROCURADOR;
 --EJ. PODEMOS CONSUTAR SOLO DETERMINADAS COLUMNAS DE UNA TABLA 
 SELECT ID_PROCURADOR, NOMBRE, TELEFONO FROM PROCURADOR;

--EJ. CONSULTAR INFORMACION DE UNA TABLA DEACUERDO DE UNA CONDICION
 SELECT * FROM PROCURADOR WHERE id_procurador=3;
 
 SELECT * FROM PROCURADOR WHERE honorarios>12000;
 
 --TAMBIEN PODEMOS CONSULTAR INFORMACION CON MAS DE UNA CONDICION
 SELECT * FROM PROCURADOR PROCURADOR WHERE honorarios>12000 AND direccion = 'CDMX';
 
 --CONSULTAR INFORMACION QUE SE ENCUENTRE U¿EN UN DETERMINADO RANGO
 SELECT * FROM PROCURADOR WHERE honorarios BETWEEN 10000 AND 20000;
 
--CONSULTAR DE CLIENTES CUYO NOMBRE UB¿NICIA CON ALGUNA LETRA
SELECT * FROM CLIENTE WHERE NOMBRE LIKE 'J%';
 
 --NOSPUEDE SERVIR PARA CONSUSLTAR CLIENTES POR LADA TELEFONICA
 SELECT * FROM CLIENTE WHERE TELEFONO LIKE '12%';
 
 --TAMBIEN PODEMOS BUSCARLOS CON AGUNA LETRA O COINCIDENCIA 
 SELECT * FROM CLIENTE WHERE NOMBRE LIKE '%A';
 
 SELECT * FROM CLIENTE WHERE DIRECCION LIKE '%CA';

--VAMOS AVER FUNCIONES DE AGREGACION 
--SELECCIONAR O CONSULTAR EL VALOR MAXIMO DE UNA COLUMNA EN ESTE CASO ESTAMOS PIDIENDO
--EL HONORARIO DE UN PROCURADOR
SELECT MAX(HONORARIOS) FROM PROCURADOR;

--CONSULTAR EL VALOR MINIO DE UNA COLUMNA 
SELECT MIN(HONORARIOS) FROM PROCURADOR; 
 
 --COMO CONSULTAR EL PROMEDIO DE LOS VALORES DE UNA COLUMNA 
 SELECT AVG (HONORARIOS) FROM PROCURADOR;
 
 --REALIZAR LA SUMATORIA DE VALORES DE UNA COLUMNA 
 SELECT SUM(HONORARIOS) FROM PROCURADOR;
 
--COMO REALIZAR UN CONTEO DE LOS REGISTROS DE UNA TABLA LOS PODEMOS CONSULTAR 
--POR ALGUNA COLUMNA ESPECIFICA O POR TODO
SELECT COUNT (ID_PROCURADOR) FROM PROCURADOR; 
 
SELECT COUNT (*) FROM PROCURADOR; 
 
 -- PODRIAMOS CONTAR CUANTOS PROCURADORES COBRAN MAS DE 10000
 SELECT COUNT (*) FROM PROCURADOR WHERE HONORARIOS>11000;
 
SELECT COUNT (ID_PROCURADOR) FROM PROCURADOR WHERE HONORARIOS<11000;

--ej. podemos utilizar un conteo PARA AGRUPAR A NUESTROS REGISTROS POR ALGUN CRITERIO 
--EN LA TABLA ASUNTO AGRUPADO POR ESTADO

SELECT COUNT (*), ESTADO FROM ASUNTO GROUP BY ESTADO;

--AGRUPAR ALGUNO POR GENERO
SELECT COUNT (*), GENERO FROM ALUMNO GROUP BY GENERO;

-- COMO PODEMOS ORDENAR NUESTROS REGISTROS DE FORMA ACCEDENTE O DESENDENTE
--DEACUERDO A UN CRITERIO O COLUMNA

--EJ. ORDENAR LOS REGISTROS DE UNA TABLA DEACUERDO A SU ID ASCENDENTE
SELECT * FROM ALUMNO ORDER BY ALUMNO_ID;
 
--EJ. ORDENAR LOS REGISTROS DE UNA TABLA DEACUERDO A SU ID DESCENDENTE
SELECT * FROM ALUMNO ORDER BY ALUMNO_ID DESC;
 
 --LOS MISMO OCURRERIA SI QUIERO ORDENAR A MIS ALUMNOS DE FORMA ALFABETICAMENTE
 SELECT * FROM ALUMNO ORDER BY NOMBRE;
 
 -------------------------------------------------------
-- CONSULTAS ANIDADAS
-- Practicamente esto es una consulta dentro de otra consulta

-- EJ. CUANDO QUEREMOS CONOCER LOS DATOS DEL PROCURADOR QUE MÁS HONORARIOS COBRA
SELECT * FROM PROCURADOR;

SELECT * FROM PROCURADOR WHERE HONORARIOS = (SELECT MAX(HONORARIOS) FROM PROCURADOR);

-- EJ2. CONOCER LOS DATOS DEL PROCURADOR QUE PARTICIPA EN EL ASUNTO 3
SELECT * FROM PROCURADOR WHERE ID_PROCURADOR IN
(SELECT PROCURADOR_ID FROM ASUNTO_PROCURADOR WHERE ID_ASUNTO IN 3);

SELECT * FROM ASUNTO_PROCURADOR;

-- VOY A INSERTAR OTRO PROCURADOR QUE PARTICIPE EN EL ASUNTO 3
INSERT INTO PROCURADOR VALUES (6, 'DANIELA', 'OAXACA, OAX', '1234567890', 13000);
SELECT * FROM ASUNTO;
INSERT INTO ASUNTO_PROCURADOR VALUES(6, 3, 3);
INSERT INTO ASUNTO_PROCURADOR VALUES(7, 3, 5);


-- PARA CUANDO NOS RETORNA MULTIPLES ID'S DE PROCURADOR, UTILIZAMOS EL PARAMETRO IN
SELECT * FROM PROCURADOR WHERE ID_PROCURADOR IN
(SELECT ID_PROCURADOR FROM ASUNTO_PROCURADOR WHERE ID_ASUNTO = 3);

-- CONSULTAR TODA LA INFORMACION DEL PROCURADOR QUE PARTICIPA EN EL ASUNTO
-- DONDE EL NOMBRE DEL CLIENTE = 'PEDRO';
-- RESOLVER CON CONSULTAS ANIDADAS
-- consultas anidadas
SELECT * FROM PROCURADOR WHERE ID_PROCURADOR IN (SELECT ID_PROCURADOR FROM ASUNTO_PROCURADOR WHERE ID_ASUNTO IN
(SELECT ID_CLIENTE FROM CLIENTE WHERE NOMBRE LIKE 'MARIO%'));


COMMIT;
-- consultas con joins
--PERMITE UNIR 2 O MAS TABLAS para regresar o consultar sierta informacion 
--INNER JOIN
 --DEVUELVE LA INFORMACION DE UNA TABLA A Y UNA TABLA B PERO SOLO LA INFORMACION COINCIDENTE 
 --EJ. UNIOR LA TABLA ALUMNO CON CARRERAS ALUMNOS A TRVES DE ALUMNO ID
 SELECT * FROM ALUMNO
 INNER JOIN CARRERAS_ALUMNOS
 ON ALUMNO.ALUMNO_ID = CARRERAS_ALUMNOS.ALUMNO_ID;
 
 -- UNIR CLIENTE CON ASUNTOS 
 SELECT * FROM CLIENTE 
 INNER JOIN ASUNTO
 ON CLIENTE.ID_CLIENTE = ASUNTO.ID_CLIENTE;
 
 --EL USO DEL LEFT JOIN
 --PRIORIZA LA TABLA IZQUIERDA M
 -- MUESTRA TODO DE LA TABLA A Y SOLO COINCIDENTE DE LA TABLA B
 SELECT * FROM ALUMNO
 LEFT JOIN CARRERAS_ALUMNOS
 ON ALUMNO.ALUMNO_ID = CARRERAS_ALUMNOS.ALUMNO_ID;
 
 --RIGHT JOIN
 --PRIORIZA LA TABLA DERECHA MUESTRA TODO DE LA TABLA B Y SOLO LO COINCIDENTE DE LA TABLA A
 SELECT * FROM ALUMNO
 RIGHT OUTER JOIN CARRERAS_ALUMNOS
 ON ALUMNO.ALUMNO_ID = CARRERAS_ALUMNOS.ALUMNO_ID;
 
 -- FULL JOIN 
 --MUESTRA TODO DE LA TABLA A Y DE LA TABLA B AUNQUE NO HAYA COINCIDENCIAS
 SELECT * FROM ALUMNO
 FULL OUTER JOIN CARRERAS_ALUMNOS
 ON ALUMNO.ALUMNO_ID = CARRERAS_ALUMNOS.ALUMNO_ID;
 
 SELECT * FROM carreras_alumnos
 RIGHT OUTER JOIN ALUMNO
 ON ALUMNO.ALUMNO_ID = CARRERAS_ALUMNOS.ALUMNO_ID;
 
 --EJ UNIR MAS DE DOS TABLAS
 --ALUMNO CON CARRERAS ALUMNO Y CON CARRERAS
 
 SELECT * FROM ALUMNO
 INNER JOIN CARRERAS_ALUMNOS
 ON ALUMNO.ALUMNO_ID = CARRERAS_ALUMNOS.ALUMNO_ID
 INNER JOIN CARRERAS
 ON CARRERAS.CARRERA_ID = CARRERAS_ALUMNOS.CARRERA_ID;
 
 --PODEMOS SOLICITAR SOLO CIERTAS COLUMNAS UNA VES FUNCIONA EL JOIN
SELECT ALUMNO.ALUMNO_ID, ALUMNO.NOMBRE, ALUMNO.GRADO, carreras.nombre FROM ALUMNO
 INNER JOIN CARRERAS_ALUMNOS
 ON ALUMNO.ALUMNO_ID = CARRERAS_ALUMNOS.ALUMNO_ID
 INNER JOIN CARRERAS
 ON CARRERAS.CARRERA_ID = CARRERAS_ALUMNOS.CARRERA_ID;
 
 -- crear la consulta identificando a nuestras tablas con un alias
SELECT A.ALUMNO_ID, A.NOMBRE, A.GRADO, C.NOMBRE FROM ALUMNO A
 INNER JOIN CARRERAS_ALUMNOS CA
 ON A.ALUMNO_ID = CA.ALUMNO_ID
 INNER JOIN CARRERAS C
 ON C.CARRERA_ID = CA.CARRERA_ID; 
 
 --AGRAGRA UN ALIAS PARA MOSTRAR EN LOS ENCABESADOS DE LOS ESTADOS DE LA CONSULTAS
 SELECT A.ALUMNO_ID AS MATRICULA, A.NOMBRE AS ALUMNO, A.GRADO AS SEMESTRE, C.NOMBRE AS CARRERA FROM ALUMNO A
 INNER JOIN CARRERAS_ALUMNOS CA
 ON A.ALUMNO_ID = CA.ALUMNO_ID
 INNER JOIN CARRERAS C
 ON C.CARRERA_ID = CA.CARRERA_ID; 
 
 --CONSULTAR TODA LA INFORMACION DEL PROCURADOR QUE PARTICIPA EN EL ASUNTO
-- DONDE EL NOMBRE DEL CLIENTE = 'PEDRO';
-- RESOLVER CON JOIN

SELECT P.*, C.NOMBRE AS NOMBRE_CLIENTE FROM PROCURADOR P
INNER JOIN ASUNTO_PROCURADOR AP 
ON P.ID_PROCURADOR = AP.ID_PROCURADOR
INNER JOIN ASUNTO A 
ON AP.ID_ASUNTO = A.ID_ASUNTO
INNER JOIN CLIENTE C 
ON A.ID_CLIENTE = C.ID_CLIENTE
WHERE C.NOMBRE LIKE 'MARIO%';

 
 
 
 
 
 
 
 
 
 
 
 



