--antes de crear el primer registro vamos a verificar el 
--formato de fecha que admite nuestro sistema
SELECT SYSDATE FROM DUAL;

--INCERTAMOS NUESTRO PRIMER REGISTRO  LA SENTENCIA 
--ES 
DESCRIBE ALUMNO;

INSERT INTO ALUMNO 
VALUES(1, 'ANDRES', '26/03/1994', 'MASCULINO', '1ER SEMESTRE', 'CDMX',1);

INSERT INTO ALUMNO 
VALUES(2, 'ALEX', '02/05/2000', 'MASCULINO', '3CER SEMESTRE', 'TOLUCA',1);

INSERT INTO ALUMNO 
VALUES(3, 'CARMEN', '02/05/2002', 'FEMENINO', '1ER SEMESTRE', 'OAXACA',1);

--

SELECT * FROM  ALUMNO;

--las sentencias  DML, QUE SON DE MANIPULACION DE DATOS SE DEVEN CONFIMAR 
--PARA QUE ESTOS CAMBIOS SE GUARDEN DEFORMA PERMANENTE
COMMIT;

-- INCERTAR VALORES EN LA TABLA CARRERAS 
DESCRIBE CARRERAS;

INSERT INTO CARRERAS 
VALUES(1, 'ING. EN SISTEMAS', 'EXACTAS', '8 SEMESTRES', 200000.99);

INSERT INTO CARRERAS 
VALUES(2, 'MEDICINA', 'BIOLOGIA', '10 SEMESTRES', 300000.99);

INSERT INTO CARRERAS 
VALUES(3, 'ADMINISTRACION', 'ECONOMIAS', '8 SEMESTRES', 100000.99);



COMMIT;
SELECT * FROM CARRERAS;

-- INCERRTAR VALORES EN LA TABLA TRELACIONAL EN LA TABLA CARRERAS_ALUMNOS
DESCRIBE CARRERAS_ALUMNOS;

INSERT INTO CARRERAS_ALUMNOS 
VALUES(1,1,3);
INSERT INTO CARRERAS_ALUMNOS 
VALUES(2,2,3);
INSERT INTO CARRERAS_ALUMNOS 
VALUES(3,3,1);

COMMIT;-- GUARDA LOS CAMBIOS 
DESCRIBE CARRERAS_ALUMNOS;
SELECT * FROM CARRERAS_ALUMNOS;






