--Comentarios de una sola linea
-- comentarios de una sola linea con dos guiones medios seguidos--

/*
Comentarios
de 
multiples
lineas
*/

--SQL (LENGUAJE DE CONSULTA ESTRUCTURADO)
-- Bases de datos relacionales - connjunto de datos relacionados
--entre si y que son almacenados en tablas

--ESTRUCTURA DE UNA TABLA EN BD
--Toda tabla debe llevar llave primaria - primary Key
--Que es un identificador unico de cada registro que vamos guardando
--Puede llevar llave foranea - Foreign Key
--la llave foranea es una llave primaria que proviene de otra tabla
--columnas con su diferente tipo de dato

--TIPOS DE DATOS EN BD ORACLE
--NUMBER - Permite almacenar datos numericos enteros y decimales
--VARCHAR2- NVARCHAR2 - Este ultimo admite caracteres alfanumericos
-- y caracteres especiales y además optimiza la memoria
--DATE - Manejo de fecha y hora
--CTRL + S para guardar nuestro script sql

--Vamos a crear una primera tabla de ejemplo para guardar
--la info de Alumnos de una escuela o universidad

--Sintaxis para crear una tabla es la sig:

/*
CREATE TABLE nombre Tabla(
nombreColumna tipoDato,
columna2 tipoDato,
.
.
);
*/

-- ALUMNOS
-- MATRICULA O ID DEL ALUMNO
-- NOMBRE
-- FECHA DE NACIMIENTO
-- GENERO
-- GRADO
-- CIUDAD
-- STATUS - ESTE SERÁ NUMERICO PARA SABER SI EL ALUJMNO ESTÁ
-- INSCRITO SI->(1) O NO->(0)

-- Se recomienda que las sentencias sql se escriban en mayusculas
-- porque luego esto lo comunicaremos con Java y entonces existe
-- sensibilidad al uso de mayusculas y minusculas

CREATE TABLE ALUMNO(
ALUMNO_ID NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(30),
FECHANAC DATE,
GENERO NVARCHAR2(18),
GRADO NVARCHAR2(30),
CIUDAD NVARCHAR2(30),
STATUS NUMBER
);

--VER LA ESTRUCTURA DE UNA TABLA
DESCRIBE ALUMNO;

--RENOMBRAR UNA TABLA
ALTER TABLE ALUMNO RENAME TO ALUMNOS;

--ELIMINAR UNA TABLA CON TODO Y SU CONTENIDO
DROP TABLE ALUMNOS;

-- CREAR UNA TABLA PARA ALMACENAR CARRERAS
CREATE TABLE CARRERAS(
CARRERA_ID NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(30),
AREA NVARCHAR2(30),
DURACION NVARCHAR2(30)
);

-- RENOMBRAR UNA COLUMNA DE UNA TABLA
ALTER TABLE CARRERAS RENAME COLUMN DURACION TO SEMESTRES;

-- AGREGAR UNA COLUMNA A UNA TABLA EXISTENTE CON UN TIPO DE DATO
-- DELIMITANDO (NUMBRE), 8 POSICIONES Y DE ELLAS 2 SERAN DECIMALES
ALTER TABLE CARRERAS ADD PRESUPUESTO NUMBER (8,2);

--MODIFICAR EL TIPO DE DATO DE UNA COLUMNA, SIEMPRE Y CUANDO
-- NO TENGA DATOS
ALTER TABLE CARRERAS MODIFY SEMESTRES NUMBER;

DESCRIBE CARRERAS;

ALTER TABLE CARRERAS MODIFY SEMESTRES NVARCHAR2(50);

-- CREAR UNA TERCERA TABLA RELACIONAL PARA TENER LA POSIBILIDAD
-- DE UNA CARDINALIDAD 1 A MUCHOS 1:M (1 ALUMNO Y MUCHAS O VARIAS CARRERAS)
CREATE TABLE CARRERAS_ALUMNOS(
CA_ID NUMBER PRIMARY KEY, 
ALUMNO_ID NUMBER,
CARRERA_ID NUMBER
);

-- CREACION DE RESTRICCIONES
-- NOS VAN A PERMITIR INTRODUCIR SOLO DETERMINADOS VALORES EN NUESTRAS COLUMNAS

-- RESTRICCIONES DE TIPO CHECK (VALIDAN UN VALOR)
-- EJ. EN LA TABLA ALUMNO VAMOS A CREAR UNA RESTRICCION PARA QUE EN LA COLUMNA GENERO
-- SOLO PODAMOS INSERTAR EL VALOR MASCULINO O FEMENINO

ALTER TABLE ALUMNO ADD CONSTRAINT CHK_GENERO
CHECK (GENERO IN('MASCULINO','FEMENINO'));

-- RESTRICCIONES UNIQUE
-- SIRVEN PARA EVITAR QUE UN VALOR QUE NO ES LLAVE PRIMARIA
-- SE REPITA. EJ. NOMBRE DE LAS CARRERAS
ALTER TABLE CARRERAS ADD CONSTRAINT UNQ_NOMBRE_CARRERAS
UNIQUE (NOMBRE);

-- EJ. CREANDO LAS LLAVES FORANEAS EN LA TABLA CARRERAS_ALUMNOS
-- PRIMERO LA LLAVE FORANEA PARA RECIBIR LA INFO DEL ALUMNO

ALTER TABLE CARRERAS_ALUMNOS ADD CONSTRAINT FK_ALUMNO_ID_CA
FOREIGN KEY (ALUMNO_ID)
REFERENCES ALUMNO (ALUMNO_ID);

-- SEGUNDO LA LLAVE FORANEA PARA RECIBIR LA INFO DE LA CARRERA
ALTER TABLE CARRERAS_ALUMNOS ADD CONSTRAINT FK_CARRERA_ID_CA
FOREIGN KEY (CARRERA_ID)
REFERENCES CARRERAS (CARRRERA_ID);

DESCRIBE CARRERAS;

-- SENTENCIAS DML (DATA MANIPULATION LANGUAGE)
-- Comandos que nos permiten realizar operaciones CRUD en nuestras tablas
-- Create, Read, Update, Delete (Crear, leer o consultar, actualizar y eliminar)

-- Vamos a insertar nuestros primeros registros en nuestras tablas
-- Ej. Insertar un primer Alumno
-- Antes de crear el primer registro, vamos a verificar el formato de fecha
-- que admite nuestro sistema

SELECT SYSDATE FROM DUAL;

-- INSERTAMOS NUESTRO PRIMER REGISTRO EN LA TABLA ALUMNO
DESCRIBE ALUMNO;

INSERT INTO ALUMNO 
VALUES (1, 'ANDRES', '26/03/1994', 'MASCULINO', '1ER SEMESTRE', 'CDMX', 1);

INSERT INTO ALUMNO 
VALUES (2, 'ALEX', '24/04/2000', 'MASCULINO', '3ER SEMESTRE', 'PUEBLA', 1);

INSERT INTO ALUMNO 
VALUES (3, 'CARMEN', '02/07/2002', 'FEMENINO', '1ER SEMESTRE', 'OAXACA', 1);

-- CONSULTA GENERAL DE TODAS LAS COLUMNAS DE UNA TABLA

SELECT * FROM ALUMNO;

-- LAS SENTENCIAS DML, QUE SON DE MANIPULACION DE DATOS SE DEBEN CONFIRMAR PARA QUE
-- ESTOS CAMBIOS SE GUARDEN DE FORMA PERMANENTE EN LA BD
COMMIT;

DESCRIBE CARRERAS;


INSERT INTO CARRERAS VALUES (1, 'ING EN SISTEMAS', 'EXACTAS', '8 SEMESTRES', 200000.99 );
INSERT INTO CARRERAS VALUES (2, 'MEDICINA', 'BIOLOGICAS', '10 SEMESTRES', 300000.99 );
INSERT INTO CARRERAS VALUES (3, 'ADMINISTRACION', 'ECONOMICAS', '8 SEMESTRES', 100000.99 );

-- EJ. DE QUE NO SE PUEDE REPETIR LOS NOMBRES DE LAS CARRERAS Y FUNCIONA 
-- LA RESTRICCION UNIQUE
INSERT INTO CARRERAS VALUES (4, 'ADMINISTRACION', 'ECONOMICAS', '8 SEMESTRES', 100000.99);

COMMIT;

SELECT * FROM CARRERAS;

-- INSERTAR VALORES EN LA TABLA RELACIONAL CARRERAS_ALUMNOS
DESCRIBE CARRERAS_ALUMNOS;

INSERT INTO CARRERAS_ALUMNOS VALUES (1, 1, 3);
INSERT INTO CARRERAS_ALUMNOS VALUES (2, 2, 3);
INSERT INTO CARRERAS_ALUMNOS VALUES (3, 3, 1);

COMMIT;
SELECT * FROM CARRERAS_ALUMNOS;




-- EJERCICIO BD ALUMNOS 

CREATE TABLE TUTORES(
TUTOR_ID NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(30),
EMAIL NVARCHAR2(50),
CLAVE NVARCHAR2(1)
);

-- RESTRICCION CHECK CLAVE TUTOR
ALTER TABLE TUTORES ADD CONSTRAINT CHK_CLAVE
CHECK (CLAVE IN('A', 'B', 'C', 'D'));

DESCRIBE TUTORES;

INSERT INTO TUTORES VALUES (1, 'ANTONIO', 'ANTONIO@HOTMAIL.COM', 'A');
INSERT INTO TUTORES VALUES (2, 'MARIA', 'AMARIMATH@HOTMAIL.COM', 'B');
INSERT INTO TUTORES VALUES (3, 'FRANCISCO', 'PACOCHATO@GMAIL.COM', 'C');
INSERT INTO TUTORES VALUES (4, 'LUSINA', 'LUSILOVE@GMAIL.COM', 'D');
INSERT INTO TUTORES VALUES (5, 'ISABEL', 'QISQFB@GMAIL.COM', 'A');

-- PROBANDO RESTRICCION CHECK EN CLAVE
INSERT INTO TUTORES VALUES (6, 'JULIAN', 'JULLAY@OUTLOOK.COM', 'X');

COMMIT;
SELECT * FROM TUTORES;


CREATE TABLE TUTORES_ALUMNOS(
TA_ID NUMBER PRIMARY KEY,
TUTOR_ID NUMBER,
ALUMNO_ID NUMBER
);
DESCRIBE TUTORES_ALUMNOS;

-- FOREIGN KEY REALCION TUTOR ID
ALTER TABLE TUTORES_ALUMNOS ADD CONSTRAINT FK_TUTOR_ID_TA
FOREIGN KEY (TUTOR_ID)
REFERENCES TUTORES (TUTOR_ID);

-- FOREIGN KEY REALCION TUTOR -> ALUMNO
ALTER TABLE TUTORES_ALUMNOS ADD CONSTRAINT FK_ALUMNO_ID_TA
FOREIGN KEY (ALUMNO_ID)
REFERENCES ALUMNO (ALUMNO_ID);

INSERT INTO TUTORES_ALUMNOS VALUES (1, 4, 1);
INSERT INTO TUTORES_ALUMNOS VALUES (2, 2, 3);
INSERT INTO TUTORES_ALUMNOS VALUES (3, 1, 2);

COMMIT;
SELECT * FROM TUTORES_ALUMNOS;

CREATE TABLE STATUS_ALUMNOS(
STATUS_ID NUMBER PRIMARY KEY,
DESCRIPCION NVARCHAR2(30)
);

INSERT INTO STATUS_ALUMNOS VALUES (0, 'ALUMNO NO INSCRITO');
INSERT INTO STATUS_ALUMNOS VALUES (1, 'ALUMNO INSCRITO');

-- FOREIGN KEY STATUS ALUMNO
ALTER TABLE ALUMNO ADD CONSTRAINT FK_STATUS_ID_SA
FOREIGN KEY (STATUS)
REFERENCES STATUS_ALUMNOS (STATUS_ID);

COMMIT;
SELECT * FROM STATUS_ALUMNOS;

-- PROBANDO FOREIGN KEY STATUS ALUMNOS
INSERT INTO ALUMNO VALUES (4, 'CLAUDIA', '02/07/2002', 'FEMENINO', '1ER SEMESTRE', 'OAXACA', 3);

-- EJ. SINTAXIS DE CREACION DE TABLA CON RESTRICCIONES AL PRINCIPIO

--    CREATE TABLE TUTORES(
--    TUTOR_ID NUMBER PRIMARY KEY,
--    NOMBRE NVARCHAR2(30),
--    EMAIL NVARCHAR2(50),
--    CLAVE NVARCHAR2(1),
--    CONSTRAINT CHK_CLAVE_TUTOR CHECK (CLKAVE IN('A', 'B', 'C', 'D'))
--    );

-- EJ. SINTAXIS DE CREACION DE TABLA CON LLAVE FORANEA AL PRINCIPIO

    --CREATE TABLE TUTORES_ALUMNOS(
    --TA_ID NUMBER PRIMARY KEY,
    --TUTOR_ID NUMBER,
    --ALUMNO_ID NUMBER,
    --CONSTRAINT FK_TUTOR_ID_TA
    --FOREIGN KEY (TUTOR_ID)
    --REFERENCES TUTORES (TUTOR_ID),
    --FOREIGN KEY (ALUMNO_ID)
    --REFERENCES ALUMNO (ALUMNO_ID)
    --);

--CREACION DE LA TABLA STATUS_ALUMNO NOS VA A SERVIR COMO CATALOGO PARA SABER
-- QUE SIGNIFICAN LOS STATUS DE CADA ALUMNO Y ADEMÁS SI CREAMOS LA LLAVE FORANEA
-- EN LA TABLA ALUMNO, PUES RESTRINGIMOS QUE SOLO PUEDAN TOMARSE VALORES PREVIAMENTE
-- EXISTEN EN STATUS_ALUMNOS

--    CREATE TABLE STATUS_ALUMNOS(
--    STATUS_ID NUMBER PRIMARY KEY,
--    DESCRIPCION NVARCHAR2(30)
--    );

--PRIMERO DEBEMOS INSERTAR LOS IDS, YA QUE EXISTEN VALORES EN LA TABLA ALUMNO
--ANTES DE CREAR LA LLAVE FORANEA

--    INSERT INTO STATUS_ALUMNOS VALUES (0, 'ALUMNO NO INSCRITO');
--    INSERT INTO STATUS_ALUMNOS VALUES (1, 'ALUMNO INSCRITO');
    
--    SELECT * FROM STATUS_ALUMNO;
--    
--    ALTER TABLE ALUMNO ADD CONSTRAINT FK_STATUS_ID_SA
--    FOREIGN KEY (STATUS)
--    REFERENCES STATUS_ALUMNOS (STATUS_ID);

-- CREACION DE SECUENCIAS
-- LAS SECUENCIAS SON OBJETOS QUE NOS PERMITEN GENERAR VALORES DE
-- NUMEROS ENTEROS EN FORMA CONSECUTIVA CON UN INCRTEMENTO DETERMINADO
-- (DE 1 EN 1, DE 2 EN 2, ETC).
-- SE UTILIZAN PARA, EN ESTE CASO, GENERAR LAS LLAVES PRIMARIAS Y DE ESTA 
-- FORMA NOS ASEGURAMOS QUE LOS VALORES NO SE REPITAN

-- VAMOS A CREAR U NA SECUENCIA PARA UNA TABLA QUE YA TIENE REGISTROS
-- INSERTADOS. SE CREA UNA SECUENCIA CON VALORES DEFINIDOS

SELECT * FROM ALUMNO;

CREATE SEQUENCE ALUMNO_SEQ -- NOMBRE DE LA SECUENCIA
START WITH 4 -- DESDE QUE VALOR INICIA
INCREMENT BY 1  -- DE CUANTO EN CUANTO INCREMENTA
MAXVALUE 999 -- VALOR MAXIMO
MINVALUE 1 -- VALOR MINIMO
NOCYCLE; -- CICLAR -> CYCLE, NO CICLAR -> NOCYCLE

-- EJ. DE CREAR UNA SECUENCIA CON VALORES DEFAULT. LA CUAL ES UTIL
-- PARA TABLAS QUE NO TIENEN DATOS AGREGADOS
    --CREATE SEQUENCE COMPRAS_SEQ

-- CREACION DE TRIGERS O DISPARADORES
-- SON UN TIPO DE PROCEDIMIENTO ALMACENADO QUE DESENCADENA UN EVENTO
-- EN ESTE CASO LO UTILIZAREMOS PARA INSERTAR LAS LLAVES PRIMARIAS
-- EJ. CREACION DEL DISPARADOR PARA INSERTAR LOS ID'S EN LA TABLA ALUMNO

    --CREATE OR REPLACE TRIGGER INSERT_ALUMNO -- NOMBRE DEL TRIGGER
    --BEFORE INSERT ON ALUMNO FOR EACH ROW BEGIN -- DONDE ACTUA
    --SELECT ALUMNO_SEQ.NEXTVAL INTO:NEW.ALUMNO_ID FROM DUAL; -- QUE HACE? 
    ----TOMA EL VALOR DE LA SECUENCIA PARA INSERTARLO EN UN NUEVO ID
    --END;

CREATE OR REPLACE TRIGGER INSERT_ALUMNO 
BEFORE INSERT ON ALUMNO FOR EACH ROW BEGIN 
SELECT ALUMNO_SEQ.NEXTVAL INTO:NEW.ALUMNO_ID FROM DUAL;
END;

-- EJ. INSERTAR UN NUEVO ALUMNO, PERO EXPERIMENTANDO COMO ELTRIGGER YA HACE LA
-- INSERCION POR NOSOTROS

INSERT INTO ALUMNO 
VALUES (1, 'HUGO', '12/12/2002', 'MASCULINO', '4O SEMESTRE', 'CHIAPAS', 1);

SELECT * FROM ALUMNO;

-- EJ. QUE PASA SI QUIERO REGISTRAR UN NUEVO ALUMNO Y OMITIR EL ID
INSERT INTO ALUMNO 
VALUES ('ALMA', '12/12/2002', 'FEMENINO', '4O SEMESTRE', 'CHIAPAS', 1);

-- PUEDO OMITIR EL ID, INDICANDO QUE COLUMNAS VOY A INSERTAR UNICAMENTE
INSERT INTO ALUMNO (NOMBRE, FECHANAC, GENERO, GRADO, CIUDAD, STATUS) VALUES
('ALMA', '12/12/2002', 'FEMENINO', '4O SEMESTRE', 'CHIAPAS', 1);

SELECT * FROM ALUMNO;

COMMIT;

--ELIMINAR UN REGISTRO DE UNA TABLA. CASI SIEMPRE ES RECOMENDABLE IDENTIFICAR
-- A NUESTRO REGISTRO POR ID

DELETE FROM ALUMNO WHERE ALUMNO_ID=5;

--EJ. INTENTAR BORRAR EL REGISTRO 1 QUE YA TIENE UNA CARRERA ASIGNADA Y/O TUTOR

--SI QUEREMOS RECUPERAR UN REGISTRO ELIMINADO O UNA ACTUALIZACION, HAY UNA
--INSTRUCCION QUE NOS LLEVA AL ESTADO DEL ULTIMO COMMIT. EJ. AQUI AUN NO HE CONFRIMADO
--EL BORRADO DE MIS ALUMNOS
ROLLBACK;

SELECT * FROM ALUMNO;
COMMIT;

DELETE FROM ALUMNO WHERE ALUMNO_ID=7;

-- PODEMOS EDITAR LA SECUENCIA SI QUEREMOS RECUPERAR EL CONSECUTIVO DE NUMERO
-- LO HACEMOS DESDE EL PANEL DE CONEXIONES EN EL APARTADO DE SECUENCIAS

-- ACTUALIZAR VALORES DE UN REGISTRO
-- EJ. VOY A EDITAR DE ALMA LA CIUDAD
UPDATE ALUMNO SET CIUDAD = 'CHIHUAHUA' WHERE ALUMNO_ID = 5;

SELECT * FROM ALUMNO;

-- CONFIRMAMOS EL CAMBIO
COMMIT;

-- EJ. DE ACTUALIZACION DE VARIOS VALORES AL MISMO TIEMPO
UPDATE ALUMNO SET CIUDAD = 'XALAPA', GRADO = '5O SEMESTRE', STATUS = 0 WHERE ALUMNO_ID = 5;

-- VAMOS A VER QUE OCURRE SI CREO UNA SECUENCIA CON VALORES POR DEFECTO
-- ES DECIR, QUE INICIE DESDE EL 1, Y CREO TAMBIEN UN DISPARADOR
-- EJ. PARA LAS CARRERAS
CREATE SEQUENCE CARRERAS_SEQ;

SELECT* FROM CARRERAS;

-- CREAR TRIGGER PARA LA TABLA CARRERAS
CREATE OR REPLACE TRIGGER INSERT_CARRERAS
BEFORE INSERT ON CARRERAS FOR EACH ROW BEGIN 
SELECT CARRERAS_SEQ.NEXTVAL INTO:NEW.CARRERA_ID FROM DUAL;
END;

-- INTENTAMOS INSERTAR UNA CARRERA, EL DISPARADOR LO INTENTARÁ INSERTAR CON EL ID 1
-- ASÍ QUE TENDREMOS QUE LLEGAR AL VALOR HASTA QUE SEA EL CORRECTO
INSERT INTO CARRERAS VALUES (1, 'GASTRONOMIA', 'ECONOMICAS', '9 SEMESTRES', 110000.89);

-- EJERCICIO ASUNTOS ABOGADOS

-- CREACION DE ENTIDADES FUERTES
CREATE TABLE CLIENTE (
CLIENTE_ID NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(50),
DIRECCION NVARCHAR2(50),
TELEFONO NVARCHAR2(12)
);

-- CREACION DE SECUENCIA Y TRIGGER
CREATE SEQUENCE CLIENTE_SEQ;

CREATE OR REPLACE TRIGGER INSERT_CLIENTE 
BEFORE INSERT ON CLIENTE FOR EACH ROW BEGIN 
SELECT CLIENTE_SEQ.NEXTVAL INTO:NEW.CLIENTE_ID FROM DUAL;
END;

-- SIGUIENTE ENTIDAD FUERTE
CREATE TABLE PROCURADORES (
PROCURADOR_ID NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(50),
DIRECCION NVARCHAR2(50),
TELEFONO NVARCHAR2(12),
HONORARIOS NUMBER
);

-- CREACION DE SECUENCIA Y TRIGGER
CREATE SEQUENCE PROCURADORES_SEQ;

CREATE OR REPLACE TRIGGER INSERT_PROCURADOR
BEFORE INSERT ON PROCURADORES FOR EACH ROW BEGIN 
SELECT PROCURADORES_SEQ.NEXTVAL INTO:NEW.PROCURADOR_ID FROM DUAL;
END;

-- CREACION DE ENTIDADES DEBILES

CREATE TABLE ASUNTOS (
ASUNTO_ID NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(30),
FECHA_INICIO DATE,
FECHA_FIN DATE,
ESTADO NVARCHAR2(12),
CLIENTE_ID NUMBER,
CONSTRAINT FK_CLIENTE_ID FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (CLIENTE_ID),
CONSTRAINT CHK_ESTADO CHECK (ESTADO IN('ARCHIVADO', 'EN TRAMITE', 'FINALIZADO'))
);

-- CREACION DE SECUENCIA Y TRIGGER
CREATE SEQUENCE ASUNTOS_SEQ;

CREATE OR REPLACE TRIGGER INSERT_ASUNTO
BEFORE INSERT ON ASUNTOS FOR EACH ROW BEGIN 
SELECT ASUNTOS_SEQ.NEXTVAL INTO:NEW.ASUNTO_ID FROM DUAL;
END;

-- SIGUIENTE ENTIDAD DEBIL
CREATE TABLE ASUNTOS_PROCURADORES (
AP_ID NUMBER PRIMARY KEY,
PROCURADOR_ID NUMBER,
ASUNTO_ID NUMBER,
CONSTRAINT FK_ASUNTOS_ID FOREIGN KEY (ASUNTO_ID) REFERENCES ASUNTOS (ASUNTO_ID),
CONSTRAINT FK_PROCURADOR_ID FOREIGN KEY (PROCURADOR_ID) REFERENCES PROCURADORES (PROCURADOR_ID)
);

-- CREACION DE SECUENCIA Y TRIGGER
CREATE SEQUENCE AP_SEQ;

CREATE OR REPLACE TRIGGER INSERT_AP
BEFORE INSERT ON ASUNTOS_PROCURADORES FOR EACH ROW BEGIN 
SELECT AP_SEQ.NEXTVAL INTO:NEW.AP_ID FROM DUAL;
END;

-- INSERCION DE REGISTROS POR TABLA
-- CLIENTES

INSERT INTO CLIENTE VALUES (0, 'ANTONIO', 'AV. 20 DE NOVIEMBRE NO. 1060', '912-875-2180');
INSERT INTO CLIENTE VALUES (0, 'MARIA', 'AV. INDEPENDENCIA NO. 241', '912-875-4046');
INSERT INTO CLIENTE VALUES (0, 'FRANCISCO', 'AV. 5 DE MAYO NO. 1652', '912-875-1634');
INSERT INTO CLIENTE VALUES (0, 'LUSINA', 'CALLE OCAMPO NO 14', '912-875-3688');
INSERT INTO CLIENTE VALUES (0, 'ISABEL', 'AV. 5 DE MAYO NO. 1226', '912-875-1881');

SELECT * FROM CLIENTE;
COMMIT;

-- PROCURADORES

INSERT INTO PROCURADORES VALUES (0, 'REGINA', 'AV. LIBERTAD NO. 56', '376-145-5655', 47751.52);
INSERT INTO PROCURADORES VALUES (0, 'SANTIAGO ', 'INDEPENDENCIA 1519', '846-159-5133', 34124.56);
INSERT INTO PROCURADORES VALUES (0, 'MERCEDES', 'CALLE ALDAMA NO. 144-A', '543-794-3114', 24945.14);
INSERT INTO PROCURADORES VALUES (0, 'RAUL', 'CALLE HIDALGO NO.96', '730-026-2611', 55477.96);
INSERT INTO PROCURADORES VALUES (0, 'TRINIDAD', '	CALLE MATAMOROS NO. 40', '727-789-0276', 32243.57);

SELECT * FROM PROCURADORES;
COMMIT;
    
-- ASUNTOS
INSERT INTO ASUNTOS VALUES (0, 'CUSTODIA', '21/10/20', '25/11/20', 'FINALIZADO', 1);
INSERT INTO ASUNTOS VALUES (0, 'ROBO', '12/03/07', '19/05/07', 'ARCHIVADO', 2);
INSERT INTO ASUNTOS VALUES (0, 'DIVORCIO', '21/09/20', '29/10/24', 'EN TRAMITE', 3);
INSERT INTO ASUNTOS VALUES (0, 'DELITO MENOR', '05/03/21', '09/05/21', 'FINALIZADO', 4);
INSERT INTO ASUNTOS VALUES (0, 'PENSION', '12/10/24', '25/11/24', 'EN TRAMITE', 5);

SELECT * FROM ASUNTOS;
COMMIT;

INSERT INTO ASUNTOS_PROCURADORES VALUES(0, 1, 2);
INSERT INTO ASUNTOS_PROCURADORES VALUES(0, 2, 2);
INSERT INTO ASUNTOS_PROCURADORES VALUES(0, 3, 1);
INSERT INTO ASUNTOS_PROCURADORES VALUES(0, 4, 3);
INSERT INTO ASUNTOS_PROCURADORES VALUES(0, 5, 4);
INSERT INTO ASUNTOS_PROCURADORES VALUES(0, 3, 5);

SELECT* FROM ASUNTOS_PROCURADORES;
COMMIT;

-- ELIMINAR UNA COLUMNA CON DATOS, SIEMPRE Y CUANDO NO SEA FOREIGN KEY
-- Y QUE NO TENGA RESTRICCIONES DE VALOR NOT NULL
ALTER TABLE PROCURADORES DROP COLUMN CEDULA;

-- EJ. DE BORRADO ACCIDENTAL DEL FAMOSO DELETE FROM
DELETE FROM PROCURADORES; -- EL TENER LOS REGISTROS DE LOS PROCURADORES COMO LLAVE
-- FORANEA EN OTRA TABLA LOS PROTEGE DE UN BORRADO ACCIDENTAL

-- EJ. BORRADO ACCIDENTAL DE LA TABLA ASUNTOS_ PROCURADORES
-- ESTA ES UNA ENTIDAD DEBIL QUE SE COMPUNE DE LLAVES FORANEAS, Y SI PODRIA BORRASRE

DELETE FROM ASUNTOS_PROCURADORES;

SELECT * FROM ASUNTOS_PROCURADORES;


-- MIENTRAS NO CONFIRMEMOS EL BORRADO PERMANENTE DE LOS REGISTROS (COMMIT), PODEMOS
-- INSTRUIR UN BLOQUE ROLLBACK

ROLLBACK;

-- CONSULTA NDE TODOS LOS DATOS DE UNA TABLA

SELECT * FROM PROCURADORES;

-- EJ. PODEMOS CONSULTAR TAMBIÉN SOLO DETERMINADAS COLUMNAS DE UNA TABLA
SELECT PROCURADOR_ID, NOMBRE, TELEFONO FROM PROCURADORES;

-- EJ. PODEMOS CONSULTAR INFORMACION DE ACUERDO A UNA CONDICION
SELECT * FROM PROCURADORES WHERE PROCURADOR_ID IN 3;

SELECT * FROM PROCURADORES WHERE HONORARIOS > 40000;

-- EJ. PODEMOS CONSULTAR INFORMACION DE ACUERDO A MAS DE UNA CONDICION
SELECT * FROM PROCURADORES WHERE HONORARIOS > 10000 AND DIRECCION='CALLE HIDALGO NO.96';

-- EJ. PODEMOS CONSULTAR INFORMACION QUE SE ENCUENTRE EN UN DETERMINADO RANGO
SELECT * FROM PROCURADORES WHERE HONORARIOS BETWEEN 30000 AND 50000;

-- CONSULTA DE CLIENTES CUYO NOMBRE INICIA CON ALGUNA LETRA
SELECT * FROM CLIENTE WHERE NOMBRE LIKE 'L%';

-- NOS PUEDE SERVIR TAMBIEN PARA CONSULTAR CLIENTES POR LADA TELEFONICA
SELECT * FROM CLIENTE WHERE TELEFONO LIKE '9%';

-- EJ. PODEMOS BUSCARLOS SI FINALIZAN CON ALGUNA LETRA O COINCIDENCIA
SELECT * FROM CLIENTE WHERE NOMBRE LIKE '%O';

-- FUNCIONES DE AGREGACIÓN
-- SELECCIONAR O CONSULTAR EL VALOR MAXIMO DE UNA COLUMNA
SELECT MAX (HONORARIOS) FROM PROCURADORES; -- ESTO NOS DEVUELVE EL MAYOR INGRESO
-- DE UN PROCURADOR
-- CONSULTAR EL VALOR MINIMO
SELECT MIN (HONORARIOS) FROM PROCURADORES;

-- COINSULTAR EL PROMEDIO DE LOS VALORES DE UNA COLUMNA
SELECT AVG (HONORARIOS) FROM PROCURADORES;

-- REALIZAR LA SUMATORIA DE LOS VALORES DE UNA COLUMNA
SELECT SUM (HONORARIOS) FROM PROCURADORES;

-- REALIZAR UN CONTEO DE LOPS REGISTROS DE UNA TABLA, LOS PODEMOS CONSULTAR
-- POR ALGUNA COLUMNA ESPECIFICA O POR TODO
SELECT COUNT (PROCURADOR_ID) FROM PROCURADORES;

SELECT COUNT (*) FROM PROCURADORES;

-- PODRIAMOS CONTAR CUANTOS COBRAN MAS O MENOS DE 11000
SELECT COUNT (*) FROM PROCURADORES WHERE HONORARIOS>11000;
SELECT COUNT (*) FROM PROCURADORES WHERE HONORARIOS<11000;

-- EJ. POLDEMOS UTILIZAR UN CONTEO PARA AGRUPAR A NUESTROS REGISTROS POR ALGUN
-- CRITERIO. EN LA TABLA ASUNTOS AGRUPARLOS POR ESTADO
SELECT COUNT (*), ESTADO FROM ASUNTOS GROUP BY ESTADO;

-- EJ. 2 AGRUPAR ALUMNOS POR GENERO
SELECT COUNT (*), GENERO FROM ALUMNO GROUP BY GENERO;


-- EJEMPLO ORDENAR LOS REGISTROS DE UNA TABLA DE ACUERDO A SU ID ASCENDENTE
SELECT * FROM ALUMNO ORDER BY ALUMNO_ID;

-- EJEMPLO ORDENAR LOS REGISTROS DE UNA TABLA DE ACUERDO A SU ID DESCENDENTE
SELECT * FROM ALUMNO ORDER BY ALUMNO_ID DESC;

-- ORDDENAR MIS ALUMNOS POR ORDEN ALFABETICO
SELECT * FROM ALUMNO ORDER BY NOMBRE;

-- CONTEO DE PROCURADORES QUE NGANEN MAS DE 11000 Y VER EL NOMBRE
SELECT NOMBRE, COUNT (*) AS CONTEO FROM PROCURADORES WHERE HONORARIOS >11000 GROUP BY NOMBRE;

-- EJ. CUANDO QUEREMOS CONOCER LOS DATOS DEL PROCURADOR QUE MÁS HONORARIOS COBRA 
SELECT * FROM PROCURADORES;

SELECT * FROM PROCURADORES WHERE HONORARIOS = (SELECT MAX(HONORARIOS) FROM PROCURADORES);

-- EJ. 2 CONOCER LOS DATOS DEL PROCURADOR QUE PARTICIPA EN EL ASUNTO 3

SELECT * FROM PROCURADORES WHERE PROCURADOR_ID =
(SELECT PROCURADOR_ID FROM ASUNTOS_PROCURADORES WHERE ASUNTO_ID = 3);

-- VOY A INSERTAR OTRO PROCURADOR QUE PARTICIPE EN EL ASUNTO 3
INSERT INTO PROCURADORES VALUES (1, 'DANIELA', 'OAXACA, OAX', '123-456-7890', 13000);
SELECT * FROM PROCURADORES;
INSERT INTO ASUNTOS_PROCURADORES VALUES (1, 6, 3);
SELECT * FROM ASUNTOS_PROCURADORES;

-- PARA CUANDO NOS RETORNA MULTIPLES ID'S DE PROCURADOR, UTILIZAMOS EL PARAMETRO IN
SELECT * FROM PROCURADORES WHERE PROCURADOR_ID IN
(SELECT PROCURADOR_ID FROM ASUNTOS_PROCURADORES WHERE ASUNTO_ID = 3);

-- CONSULTAR TODA LA INFORMACION DEL PROCURADOR QUE PARTICIPA EN EL ASUNTO
-- DONDE EL NOMBRE DEL CLIENTE = EJ: 'PEDRO'
-- RESOLVER CON CONSULTAS ANIDADAS

SELECT * FROM PROCURADORES WHERE PROCURADOR_ID IN 
(SELECT PROCURADOR_ID FROM ASUNTOS_PROCURADORES WHERE ASUNTO_ID IN
(SELECT CLIENTE_ID FROM CLIENTE WHERE NOMBRE IN 'MARIA'));

-- CONSULTAS CON JOINS
-- PERMITEN UNIR 2 O MAS TABLAS PARA REGRESAR O CONSULTAR CIERTA INFORMACIÓN
-- UNIENDO LAS TABLAS POR UN CAMPO QUE COMPARTEN EN COMUN (PK Y FK)
-- EL PRIMER O MAS UTILIZADO ES EL INNER JOINT
-- INER JOIN :
-- ESTE DEVUELVE LA INFORMAC ION DE UNA TABLA 'A' Y UNA TABLA 'B', PERO SOLO LA INFO COINCIDENTE

-- EJ.  UNIR LA TABLA ALUMNO CON CARRERAS_ALUMNOS A TRAVÉS DE ALUMNO_ID
SELECT * FROM ALUMNO
INNER JOIN CARRERAS_ALUMNOS
ON ALUMNO.ALUMNO_ID = CARRERAS_ALUMNOS.ALUMNO_ID;

-- OTRO EJEMPLO, UNIR CLIENTE CON ASUNTOS
SELECT * FROM CLIENTE
INNER JOIN ASUNTOS
ON CLIENTE.CLIENTE_ID = ASUNTOS.CLIENTE_ID;

-- LEFT JOIN 
-- PRIORIZA LA TABLA IZQUIERDA MUESTRA TODO DE LA TABLA A
-- Y SOLO LO COINCIDENTE CON LA TABLA B
SELECT * FROM ALUMNO
LEFT JOIN CARRERAS_ALUMNOS
ON ALUMNO.ALUMNO_ID = CARRERAS_ALUMNOS.ALUMNO_ID;

-- RIGHT JOIN
-- PROPRIZA LA TABLA DERECHA -> MUESTRA TODO DE LA TABLA 'B' Y SOLO
-- LO COINCIDENTE CON LA TABLA 'A'
SELECT * FROM ALUMNO
RIGHT OUTER JOIN CARRERAS_ALUMNOS
ON ALUMNO.ALUMNO_ID = CARRERAS_ALUMNOS.ALUMNO_ID;

-- FULL JOIN O FULL OUTER JOIN
-- MUESTRA TODO DE LA TABLA A Y DE LA TABLA B, AUNQUE NO HAYA COINCIDENCIAS
SELECT * FROM ALUMNO
FULL OUTER JOIN CARRERAS_ALUMNOS
ON ALUMNO.ALUMNO_ID = CARRERAS_ALUMNOS.ALUMNO_ID;

-- EJ. UNIR MÁS DE 2 TABLAS. ALUMNO CON CARRERAS ALUMNO Y CON CARRERAS
SELECT * FROM ALUMNO
INNER JOIN CARRERAS_ALUMNOS
ON ALUMNO.ALUMNO_ID = CARRERAS_ALUMNOS.ALUMNO_ID
INNER JOIN CARRERAS
ON CARRERAS.CARRERA_ID = CARRERAS_ALUMNOS.CARRERA_ID;

-- PODEMOS SOLICITAR SOLO CIERTAS COLUMNAS UNA VEZ FUNCIONA EL JOIN
SELECT ALUMNO.ALUMNO_ID, ALUMNO.NOMBRE,ALUMNO.GRADO, CARRERAS.NOMBRE FROM ALUMNO
INNER JOIN CARRERAS_ALUMNOS
ON ALUMNO.ALUMNO_ID = CARRERAS_ALUMNOS.ALUMNO_ID
INNER JOIN CARRERAS
ON CARRERAS.CARRERA_ID = CARRERAS_ALUMNOS.CARRERA_ID;

-- CREAR LA CONSULTA IDENTIFICANDO A NUESTRAS TABLAS CON UN ALIAS
SELECT A.ALUMNO_ID, A.NOMBRE,A.GRADO, C.NOMBRE FROM ALUMNO A
INNER JOIN CARRERAS_ALUMNOS CA
ON A.ALUMNO_ID = CA.ALUMNO_ID
INNER JOIN CARRERAS C
ON C.CARRERA_ID = CA.CARRERA_ID;

-- AGREGAR UN ALIAS PARA MOSTRAR EN LOS ENCABEZADOS DE LAS COLUMNAS DE LA CONSULTA

SELECT A.ALUMNO_ID AS MATRICULA, A.NOMBRE AS ALUMNO,A.GRADO AS SEMESTRE, C.NOMBRE AS CARRERA FROM ALUMNO A
INNER JOIN CARRERAS_ALUMNOS CA
ON A.ALUMNO_ID = CA.ALUMNO_ID
INNER JOIN CARRERAS C
ON C.CARRERA_ID = CA.CARRERA_ID;

-- CONSULTAR TODA LA INFORMACION DEL PROCURADOR QUE PARTICIPA EN EL ASUNTO
-- DONDE EL NOMBRE DEL CLIENTE = EJ: 'PEDRO'
-- RESOLVER CON INNER JOIN O EL JOIN QUE GUSTEN

SELECT P.PROCURADOR_ID, P.NOMBRE AS ABOGADO, P.DIRECCION, P.TELEFONO, P.HONORARIOS, C.NOMBRE AS CLIENTE FROM PROCURADORES P
INNER JOIN ASUNTOS_PROCURADORES AP
ON P.PROCURADOR_ID = AP.PROCURADOR_ID
INNER JOIN ASUNTOS A
ON A.ASUNTO_ID = AP.ASUNTO_ID
INNER JOIN CLIENTE C
ON C.CLIENTE_ID = A.ASUNTO_ID
WHERE C.NOMBRE = 'MARIA';
