-- EJERCICIO BD LIBROS
-- CREACION DE TABLAS
CREATE TABLE LIBROS (
LIBRO_ID NUMBER PRIMARY KEY,
TITULO NVARCHAR2(50),
AUTOR_ID NUMBER,
COPIAS_STOCK NUMBER,
CONSTRAINT FK_AUTOR_ID
FOREIGN KEY (AUTOR_ID)
REFERENCES AUTORES (AUTOR_ID)
);

CREATE TABLE AUTORES (
AUTOR_ID NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(50),
NACIONALIDAD NVARCHAR2(50)
);

CREATE TABLE SOCIOS (
SOCIO_ID NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(50),
DIRECCION NVARCHAR2(50),
TELEFONO NVARCHAR2(12)
);

CREATE TABLE PRESTAMOS(
PRESTAMO_ID NUMBER PRIMARY KEY,
SOCIO_ID NUMBER,
LIBRO_ID NUMBER,
FECHA_PRESTAMO DATE,
FECHA_DEVOLUCION DATE,
CONSTRAINT FK_SOCIO_ID
FOREIGN KEY (SOCIO_ID)
REFERENCES SOCIOS (SOCIO_ID),
CONSTRAINT FK_LIBRO_ID
FOREIGN KEY (LIBRO_ID)
REFERENCES LIBROS (LIBRO_ID)
);

-- CREACION DE SECUENCIAS
CREATE SEQUENCE LIBROS_SEQ;
CREATE SEQUENCE AUTORES_SEQ;
CREATE SEQUENCE SOCIOS_SEQ;
CREATE SEQUENCE PRESTAMOS_SEQ;

-- CREACION DE TRIGGERS
CREATE OR REPLACE TRIGGER INSERT_LIBRO
BEFORE INSERT ON LIBROS FOR EACH ROW BEGIN 
SELECT LIBROS_SEQ.NEXTVAL INTO:NEW.LIBRO_ID FROM DUAL;
END;

CREATE OR REPLACE TRIGGER INSERT_AUTOR
BEFORE INSERT ON AUTORES FOR EACH ROW BEGIN 
SELECT AUTORES_SEQ.NEXTVAL INTO:NEW.AUTOR_ID FROM DUAL;
END;

CREATE OR REPLACE TRIGGER INSERT_SOCIO
BEFORE INSERT ON SOCIOS FOR EACH ROW BEGIN 
SELECT SOCIOS_SEQ.NEXTVAL INTO:NEW.SOCIO_ID FROM DUAL;
END;

CREATE OR REPLACE TRIGGER INSERT_PRESTAMO
BEFORE INSERT ON PRESTAMOS FOR EACH ROW BEGIN 
SELECT PRESTAMOS_SEQ.NEXTVAL INTO:NEW.PRESTAMO_ID FROM DUAL;
END;

-- INGRESAMOS AUTORES
INSERT INTO AUTORES VALUES (0,'JAMES CLEAR','ESTADOUNIDENSE');
INSERT INTO AUTORES VALUES (0,'ALFONSO GOIZUETA','ESPAÑOL');
INSERT INTO AUTORES VALUES (0,'LORENZO ACEBEDO','ESPAÑOL');
INSERT INTO AUTORES VALUES (0,'FERMINA CAÑAVERAS','ESPAÑOLA');
INSERT INTO AUTORES VALUES (0,'MANUEL LOUREIRO','ESPAÑOL');

SELECT * FROM AUTORES;
COMMIT;

-- INGRESAMOS LIBROS
INSERT INTO LIBROS VALUES (0,'HABITOS ATOMICOS',1,10);
INSERT INTO LIBROS VALUES (0,'LA SANGRE DEL PADRE',2,16);
INSERT INTO LIBROS VALUES (0,'LA SANTA COMPAÑA',3,5);
INSERT INTO LIBROS VALUES (0,'EL BARRACON DE LAS MUJERES',4,9);
INSERT INTO LIBROS VALUES (0,'CUANDO LA TORMENTA PASE',5,8);

SELECT * FROM LIBROS;
COMMIT;

-- AGREGAMOS SOCIOS
INSERT INTO SOCIOS VALUES (0, 'ANTONIO', 'AV. 20 DE NOVIEMBRE NO. 1060', '912-875-2180');
INSERT INTO SOCIOS VALUES (0, 'MARIA', 'AV. INDEPENDENCIA NO. 241', '912-875-4046');
INSERT INTO SOCIOS VALUES (0, 'FRANCISCO', 'AV. 5 DE MAYO NO. 1652', '912-875-1634');
INSERT INTO SOCIOS VALUES (0, 'LUSINA', 'CALLE OCAMPO NO 14', '912-875-3688');
INSERT INTO SOCIOS VALUES (0, 'ISABEL', 'AV. 5 DE MAYO NO. 1226', '912-875-1881');

SELECT * FROM SOCIOS;
COMMIT;

-- AGREGAMOS PRESTAMOS
INSERT INTO PRESTAMOS VALUES(0, 1, 5, '21/10/24', '25/10/24');
INSERT INTO PRESTAMOS VALUES(0, 2, 3, '22/10/24', '27/10/24');
INSERT INTO PRESTAMOS VALUES(0, 3, 4, '20/10/24', '24/10/24');
INSERT INTO PRESTAMOS VALUES(0, 4, 1, '19/10/24', '23/10/24');
INSERT INTO PRESTAMOS VALUES(0, 5, 2, '15/10/24', '20/10/24');

SELECT * FROM PRESTAMOS;
COMMIT;